### ISSUE TITLE
Structure_oM: Reinforcement for Rectangular Sections 

### ISSUE THREAD

**Issue by maryannewachter** [BHoM/BHoM#1025]
#### Description:
Test files for reinforcement in ConcreteSection cover T-profile beam and round column. However, adding longitudinal reinforcement for a ConcreteRectangularSection throws an error for being unable to generate distribution lines.

#### Steps to reproduce:
![Structure_oM-RectangularReinfError](https://user-images.githubusercontent.com/58230980/95943842-c029f800-0d9b-11eb-9789-76998f0b3f6b.png)

**Comment by IsakNaslundBh** [comment]
Hi @maryannewachter , I tested this, and can get the error, but to me it seem to happen opnly when expected, that is, when it actually is impossible to fit all the rebars in the section given the constraints of the area of required reinforcement, cover thickness, spacing as well as size of the cross sections. 

Mind sharing the script giving you errors and I can have a look?

**Comment by maryannewachter** [comment]
Was able to test this on a few rectangular sections with different reinforcing layouts. Looks like this was a user error based on not satisfying all constraints (spacing)!
