### ISSUE TITLE
Architecture_oM: Add ceiling tile object

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM#1029]
To facilitate with https://github.com/BHoM/BHoM_Engine/issues/2049 we want a `CeilingTile` object. This will also help with the removal/renaming of CustomData as Revit_TK stores the ceiling pattern as a custom data parameter.

It would be good if the Ceiling Tile object can be made up of Edges (implementing IEdge from Analytical oM) so as to match other types of handling this. Maybe the Ceiling Tile can then be an IPanel? @IsakNaslundBh what do you think on that?

Alternatively, just a simple polyline defining its geometry is enough for now.

Then the Ceiling object can have a property that includes a collection of the `CeilingTile` objects which the Revit TK can then be updated to use instead of CustomData.

**Comment by IsakNaslundBh** [comment]
> It would be good if the Ceiling Tile object can be made up of Edges (implementing IEdge from Analytical oM) so as to match other types of handling this. Maybe the Ceiling Tile can then be an IPanel? @IsakNaslundBh what do you think on that?
>
>Alternatively, just a simple polyline defining its geometry is enough for now.

Think that could make sense with the IPanel. Only thing there is that that would mean it would require a potentionally redundant lsit of IOpenings, as that is a requirement on the IPanel. If you want to go with just a perimiter curve, I would make it a IRegion.

Doing any of the above would resolve https://github.com/BHoM/BHoM_Engine/issues/2049 automatically I think, as we have a Centroid method already implemented for `IElement2D` which both `IPanel` as well as `IRegion` both are of.

Only think to keep in mind is data duplication. As both the Ceiling and the Pattern after this change would contain geometry, there is a slight risk that they could get out of sync. Would leave the decision to you though @FraserGreenroyd if that is something you think it would be worth worrying about or not, but good to keep in mind for things like setting geometry etc.

**Comment by FraserGreenroyd** [comment]
> Think that could make sense with the IPanel. Only thing there is that that would mean it would require a potentionally redundant lsit of IOpenings, as that is a requirement on the IPanel. If you want to go with just a perimiter curve, I would make it a IRegion.

True, we don't want the Openings, but I was thinking we would want Edges, but maybe not. `IRegion` would actually make a little more sense given the end result - @JohannaOlin1 will enjoy that with her recent `IRegion` work :smile:

> Doing any of the above would resolve [BHoM/BHoM_Engine#2049](https://github.com/BHoM/BHoM_Engine/issues/2049) automatically I think, as we have a Centroid method already implemented for `IElement2D` which both `IPanel` as well as `IRegion` both are of.

Agreed, part of the reason why I want to resolve this at the object level as it'll be easier :smile:

> Only think to keep in mind is data duplication. As both the Ceiling and the Pattern after this change would contain geometry, there is a slight risk that they could get out of sync. Would leave the decision to you though @FraserGreenroyd if that is something you think it would be worth worrying about or not, but good to keep in mind for things like setting geometry etc.

Hmm this is true. I think for now, we'll keep geometry on both and risk it being out of sync, but in a future sprint it is probably best to remove geometry from Ceiling, and have that be queried from the collection of ceiling tiles (as being the outer edges not connected to another tile). FYI @kayleighhoude that would need some coordination.
