### ISSUE TITLE
MEP_oM: Add generic fitting objects

### ISSUE THREAD

**Issue by tiagogrossi** [BHoM/BHoM#1034]
#### Description:
Linear object `CableTray` has been created in oM and Engine, some thinking is needed now for its fittings. Initial thoughts is to create a placeholer object that facilitates conversion from/to Revit, having at least the following properties:

`IEnumerable Type` to hold what type of fitting it is (elbow, T, etc)
`List<ICurve> Path` to allow precise pathing through fitting to cable trays, example:
![pathing1](https://user-images.githubusercontent.com/20777038/96476363-01ebf000-122d-11eb-9d33-91f9cf4300a5.jpg) ![pathing2](https://user-images.githubusercontent.com/20777038/96476367-02848680-122d-11eb-9953-12da25f973d1.jpg)

Any other properties we require as a minimum to make converts work? I reckon shape/material and other properties as discussed in #785 could be added afterwards.

**Comment by tiagogrossi** [comment]
Further thought into this, I realize that a property `List<ICurve>` would not give us the functionality that `ILink.Node` does, present in the linear objects. Should we then have instead a property `List<Node>`? I'm not sure how that would work.. thoughts @kayleighhoude and @michaelhoehn ?

**Comment by tiagogrossi** [comment]
How about the following hierarchy? Have a `Fitting` object that is used in `IConnectionProperty`?
![CableTrayFitting](https://user-images.githubusercontent.com/20777038/96617165-2f9f6a80-12fb-11eb-8897-2719cce0b079.jpeg)

**Comment by rolyhudson** [comment]
Just noting here as discussed with @tiagogrossi that this appears to be a graph / topology problem similar to structural connections discussed in the recent workshop with @adecler, @al-fisher and @IsakNaslundBh .

If we have a graph of the cable trays (or bars) we can identify for each connection (fitting / node) a subgraph of the incoming and outgoing cable trays (or bars) that would determine the geometry of the connection.

The red diagrams above capture the subgraphs.

Not entirely sure if this helps the immediate challenge - but instead I'm logging this as another graph / topo use case.
