### ISSUE TITLE
MEP_oM: Organisation of MEP Namespaces

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM#1041]
#### Description:

![image](https://user-images.githubusercontent.com/34316256/97011225-67352f00-1514-11eb-9fa9-ac278607a130.png)

The above should make room for all existing objects within the MEP oM and make room for those that we will be adding in the future

@tiagogrossi @michaelhoehn @FraserGreenroyd @TheresaBrown curious to hear your thoughts before this is actioned

This includes the removal of Node (to be replaced by Geometry oM Point)

**Comment by michaelhoehn** [comment]
Providing a detailed outline of the proposed namespaces for the MEP_oM below. After having gone through these a bit I think it's worth another discussion regarding the implementation of the MaterialFragments classes. Makes more sense to me to have a more generic ```ElementMaterial``` to eliminate redundancies as there are many more objects that will also need material properties in the future (e.g. fittings, dampers, valves, etc.).

Another point regarding Systems in general. We currently have a prototype ```MechanicalSystem``` object and an eventual ```ElectricalSystem``` object. Where did you envision these sitting @kayleighhoude? Seems with the proposed, there could be some confusion between the ```System.Duct``` and ```System.MechanicalSystem``` when used in the same workflow. Possibly solved with something like ```System.Components.Duct```?

Anyway, glad to see these getting a bit more organised and happy to implement what is decided by the larger group. 😄 

<details open>
<summary>Equipment</summary>
<pre>BH.oM.MEP.Equipment.AirHandlingUnit<br>BH.oM.MEP.Equipment.VariableAirVolumeBox<br>BH.oM.MEP.Equipment.ElectricalPanel<br>BH.oM.MEP.Equipment.Generator<br>BH.oM.MEP.Equipment.FirePump</pre>
</details>

<details closed>
<summary>Parts</summary>
<pre>BH.oM.MEP.Parts.CoolingCoil<br>BH.oM.MEP.Parts.Fan<br>BH.oM.MEP.Parts.HeatingCoil<br>BH.oM.MEP.Parts.EnergyWheel<br>BH.oM.MEP.Parts.ElectricalConnector</pre>
</details>

<details closed>
<summary>System</summary>
<pre>BH.oM.MEP.System.Duct<br>BH.oM.MEP.System.Pipe<br>BH.oM.MEP.System.Wire<br>BH.oM.MEP.System.CableTray</pre>
</details>

<details closed>
<summary>System.Fittings</summary>
<pre>BH.oM.MEP.System.Fittings.Elbow<br>BH.oM.MEP.System.Fittings.Cross<br>BH.oM.MEP.System.Fittings.Tee<br>BH.oM.MEP.System.Fittings.Tap</pre>
</details>

<details closed>
<summary>System.Dampers</summary>
<pre>BH.oM.MEP.System.Dampers.FireDamper<br>BH.oM.MEP.System.Dampers.VolumeDamper<br>BH.oM.MEP.System.Dampers.BalancingDamper</pre>
</details>

<details closed>
<summary>System.Valves</summary>
<pre>BH.oM.MEP.System.Valves.GateValve<br>BH.oM.MEP.System.Valves.GlobeValve</pre>
</details>

<details closed>
<summary>SectionProperties</summary>
<pre>BH.oM.MEP.SectionProperties.DuctSectionProperty<br>BH.oM.MEP.SectionProperties.PipeSectionProperty<br>BH.oM.MEP.SectionProperties.WireSectionProperty<br>BH.oM.MEP.SectionProperties.CableTraySectionProperty</pre>
</details>

<details closed>
<summary>Enums</summary>
<pre>BH.oM.MEP.Enums.DuctSystemTypes<br>BH.oM.MEP.Enums.PipeSystemTypes</pre>
</details>

<details closed>
<summary>MaterialFragments</summary>
<pre>BH.oM.MEP.MaterialFragments.DuctMaterial<br>BH.oM.MEP.MaterialFragments.PipeMaterial<br>BH.oM.MEP.MaterialFragments.WireMaterial<br>BH.oM.MEP.MaterialFragments.InsulationMaterial<br>BH.oM.MEP.MaterialFragments.LiningMaterial</pre>
</details>

<details closed>
<summary>Fixtures</summary>
<pre>BH.oM.MEP.Fixtures.AirTerminal<br>BH.oM.MEP.Fixtures.LightFixture<br>BH.oM.MEP.Fixtures.PlumbingFixture<br>BH.oM.MEP.Fixtures.Socket<br>BH.oM.MEP.Fixtures.Sprinkler</pre>
</details>

**Comment by tiagogrossi** [comment]
Looks nice, I think I also prefer the classification of `Systems` like you showed there :)

**Comment by FraserGreenroyd** [comment]
On quick inspection (juggling a lot today, so happy to do a more detailed discussion next week) but I'm against `DuctMaterial` and  `PipeMaterial` as object names, and I would like us to consider how the materials for MEP can fit within the framework developed up as part of the Physical Construction objects and align with the Environments namespace were possible, probably using interfaces to group things, etc.

Otherwise, this diagram looks good, and if we implement it I would enjoy seeing it on the wiki alongside the Environments diagram :smile:

**Comment by michaelhoehn** [comment]
Per conversation today, if everyone is happy we will move forward with the proposed namespaces in the drop-downs. Work will commence with the closing of https://github.com/BHoM/BHoM/pull/1045

**Comment by michaelhoehn** [comment]
Adding a note that this issue should also be resolved prior to Namespace changing as it's dealing with a couple of methods being migrated from other toolkits. 
https://github.com/BHoM/BHoM/pull/1059
