### ISSUE TITLE
Graphics_oM: RenderMesh to implement IFragment 

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM#1046]
#### Broken rules:

In order to remove the usage of CustomData (we were storing the RenderMesh in there), RenderMesh needs to implement IFragment. 

Rendermesh ~~alone does not make any sense as it really is a representation of the object, therefore can only live together with it (it is a Fragment).~~ as a concept would make more sense as Fragment than not, because it acquires full meaning when paired with the object it is representing.

This allows for compliance and removal of CustomData in TriangleNet_Toolkit (https://github.com/BHoM/TriangleNet_Toolkit/issues/51).

#### Suggestions to restore compliance:

- RenderMesh to implement IFragment.
- Remove related settings in the `RenderMeshOptions` object.

**Comment by IsakNaslundBh** [comment]
> Rendermesh alone does not make any sense as it really is a representation of the object, therefore can only live together with it (it is a Fragment).

Disagree with this statement. No reason a Render mesh can stand on its own. It is being used outside the triangle net toolkit as well where it is not appended as a fragment to an obejct.

Saying that, we have cases where something can be a fragment but still live on its own, such as the structural IMaterials that are both a full obejct in the eyes of structures, but a fragment in the eyes of physical. The same could potentially be said for this obejct. It _can_ be a fragment of something else, but it _can_ also be an object in its own right. With that kind of argumentation I see no real blocker to add IFragment to the RenderMesh

**Comment by alelom** [comment]
I think we are saying the same thing, I would need reprashing my sentence, I agreee with you

**Comment by al-fisher** [comment]
100%. RenderMesh is a classic case of Fragments! 👍

**Comment by alelom** [comment]
> Disagree with this statement. No reason a Render mesh can not stand on its own. It is being used outside the triangle net toolkit as well where it is not appended as a fragment to an obejct.

Edited the post to rectify my sentence.

To summarise our chat that we have separately:
- @IsakNaslundBh says that he says there is no reason why a RenderMesh should be limited to be paired with a BHoMObject for every single case. @alelom agrees but argues that still RenderMesh makes more sense as a Fragment. Both agreed to make it fragment because it's non-blocking for any view of it.
