### ISSUE TITLE
Geometry_oM: Extrusion - support for multiconnected profiles and variable profiles

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM#107]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
Extrusions now supporting any ICurve, this includes ployCurves
