### ISSUE TITLE
Physical_oM: Null Geometry BulkSolids Object

### ISSUE THREAD

**Issue by michaelhoehn** [BHoM/BHoM#1088]
#### Description:

Continuing from the discussion [here](https://github.com/BHoM/BHoM/pull/1050) regarding BulkSolids. Seems it would be quite useful to have a version of `BulkSolids` (or similar) that does not require any geometry but can contain volume data as a double. 

@pawelbaran has provided a use case [here](https://github.com/BHoM/Revit_Toolkit/pull/774) that introduces the concept and provides preliminary discussion. This example would help in using general material takeoffs for LCA, and even the capacity to provide quicker and safer volume overrides for material-based sensitivity studies. 

FYI: @al-fisher, @IsakNaslundBh, @FraserGreenroyd

**Comment by michaelhoehn** [comment]
Capturing a couple of notes from a chat this morning with those already mentioned in the issue thread. 

- Object is an explicit IElementM
- Is another object required? Or can a geometry null check in the engine method. 
- `ExplicitBulk` - double Volume, MaterialComposition
- Could add another method to turn an IElementM `toExplicit` type. A clear rule that if you're going to override the properties then you need to add a Convert. 
- `VolumeModifier` fragment. Where do we check for it? All engines or just the Matter engine? 
- Matter engine as the primary host to explicitly tie the concept to IElementM. 
- When you treat the object as IElementM, then you scale the volume. 

**Action Items**
- 'ExplicitBulk` - MH 4.0 Sprint 5 Task
- Change `BulkSolids` to `SolidBulk` to better suit the new object and potential workflows. MH

**Future Items**
- Any modifiers to come from the workflows themselves to inform how this should function. Future sprints.

FYI: @al-fisher @IsakNaslundBh @pawelbaran Please feel free to edit and add any specifics I may have missed!

**Comment by al-fisher** [comment]
Thanks @michaelhoehn - great summary
