### ISSUE TITLE
Environment_oM: Add PanelType Enum for adiabatic condition

### ISSUE THREAD

**Issue by rboulton-BH** [BHoM/BHoM#1106]
#### Description:

Add 'Adiabatic' to the list of available PanelType enums. This will allow for the case in thermal modelling where it is assumed that there is no heat loss through an element e.g. adjacent space is at the same temperature.

![image](https://user-images.githubusercontent.com/26925641/100383520-abd15000-3015-11eb-8651-491d8202a9e8.png)

**Comment by FraserGreenroyd** [comment]
@rboulton-BH is this not what the `air` type was meant to be doing? What would be the equivalent option in, for example, the gbXML schema for that panel type?

[Here](https://github.com/BHoM/XML_Toolkit/blob/master/XML_Adapter/Convert/GBXML/Environment/ElementType.cs#L93) we  say that adiabatic is `air` for the gbXML schema, so if we added adiabatic as an enum option, what would be the use of air going forward?

**Comment by rboulton-BH** [comment]
It's actually pretty much the opposite as the 'Air' type means there is almost zero resistance to heat transfer (i.e. heat passes freely) whereas 'Adiabatic' effectively means no heat transfer which represents the condition where both sides of a surface are at the same temperature.

In IES terminology, 'Air' = 'Hole' and 'Adiabatic' = 'Adjacent Building'. Note that in IES 'Holes' are modelled as openings on a panel and the 'Adiabatic' condition is modelled by drawing the surface coplanar to an entirely separate element with the 'Adjacent Building' type.
![image](https://user-images.githubusercontent.com/26925641/100610317-63f94400-3307-11eb-89eb-327e0732e89e.png)

Annoyingly, I can't find any reference to Adiabatic in the gbXML schema so don't quite know how to handle it for XML_Toolkit. I'll reach out to gbXML gurus to see if they have any other ideas.

Other energy/thermal simulation software all include capability to set surfaces as Adiabatic directly instead of interpreted from the geometry, couple of examples below:

TAS
![image](https://user-images.githubusercontent.com/26925641/100610551-d833e780-3307-11eb-98a9-f265c5543435.png)

EnergyPlus
https://www.energyplus.net/sites/default/files/docs/site_v8.3.0/EngineeringReference/03-SurfaceHeatBalance/index.html#adiabatic-boundary-conditions

LadybugTools / Honeybee
http://grasshopperdocs.com/components/honeybee/makeAdiabaticByType.html
