### ISSUE TITLE
Wiki : Update Coding Style Page

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#1151]
As discussed on call - need to update the https://bhom.xyz/documentation/Contributing/Development%20FAQ/Coding-Style/ including latest conventions and as suggested, list of _Do's_ and _Dont's_ potentially pointing to more details and hyperlinks on other pages etc. as needed

Assigning to @adecler to update to latest conventions from framework perspective - for then perhaps @FraserGreenroyd @IsakNaslundBh @alelom _all_ to then add more details and review

**Comment by adecler** [comment]
After a chat with @FraserGreenroyd and @alelom , we agreed that the updates made to the wiki since this issue was raise are sufficient.
