### ISSUE TITLE
Structure_oM: BarVaryingDistributedLoad doesn't have an upgrade in versioning

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM#1157]
#### Broken rules:

`BarVaryingDistributedLoad` should have been versioned after the change in https://github.com/BHoM/BHoM/pull/1075

#### Suggestions to restore compliance:
It looks like this one will need a custom converter in `BHoMUpgrader40`

**Comment by IsakNaslundBh** [comment]
Tried doing that when I changed the class, but, after the change I got a situation where one object could become multiple. As in one load would need to be split into multiple for some cases.

From what I could see, the versioning toolkit was not able to handle that situation, hence I did not put any versioning in place.

Please let me know if that is now possible, and I will fix. If not, I think we have to leave this broken.

**Comment by adecler** [comment]
Technically, you should be able to create a list object by returning a dictionary with the key `_t` set to `System.Collections.Generic.List` (plus the generic type definition). Not the most convenient stuff to do but possible 😄 

Alternatively, there is a new `Deleted` section coming for the `Upgrades.json` files so we could also add a `NoUpgrade` section that would provide some tips to the users. But I would like to keep that section as empty as possible.

**Comment by IsakNaslundBh** [comment]
> Technically, you should be able to create a list object by returning a dictionary with the key _t set to System.Collections.Generic.List (plus the generic type definition). Not the most convenient stuff to do but possible 😄

Would happily add this if that works. The objects then, what element of this new dictionary representing a list should I put them on?

**Comment by adecler** [comment]
My bad, I was sure that `List` had an `Items` property but it looks like I have spent too much time with WPF, WinForm and BsonDocument 😋 . 

In that case, it is probably best to list that one as needing a manual upgrade.

**Comment by adecler** [comment]
Closing this as versioning becomes a bit irrelevant two years down the line
