### ISSUE TITLE
MEP_oM: DuctMaterial is not a BH.oM.Physical.Materials.Material

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM#1158]
After investigating why `DuctSectionProperty` from version 3.3 is not deserialising, I found out that the `DuctSectionProperty` is expecting a `BH.oM.Physical.Materials.Material` for its `BH.oM.Physical.Materials.Material` property BUT `DuctMaterial` is not a `Material` itself:

![image](https://user-images.githubusercontent.com/16853390/104799517-a371e600-580a-11eb-9f38-3d04b22df9bd.png)

It was possible in 3.3 so not sure what is going on here.

**Comment by FraserGreenroyd** [comment]
It appears on investigation for this one that the `DuctSectionProperty` originally accepted an `IMEPMaterial` in the property of `DuctMaterial`, but now only accepts a `BH.oM.Physical.Materials.Material`. So the property name hasn't changed, but the property type has.

I'm thinking the best thing to do is a custom converter that takes the data from the `DuctMaterial` and assigns it to a new Physical Material.
