### ISSUE TITLE
Environment_oM: Create objects to enable analysis mesh with timestep result workflows

### ISSUE THREAD

**Issue by enarhi** [BHoM/BHoM#1198]
#### Description:
Per workshop 2/17/21 for managing analysis results for meshes and analysis grids, we need to create a set of result objects to streamline handling results at nodes across a grid over a stretch of time (ie hourly for a year). 

Possible structure as discussed on the call:
General result object with result value(s) per analyses and timesteps with datetime included
Nodes each contain a Point location and Result object above
Analysis Grid containing nodes

Relates to #1189 

Test cases for this include combined daylighting and artificial lighting analysis, external microclimate analysis (many points with various values per different metrics / analyses), raw data including datetime and value for POE, and space level results translated from IES.

**Comment by tg359** [comment]
Here's a (really dodgy) example file that generates some annual hourly radiation results across a few AnalysisGrids ready to start playing with some prototyped results objects:

[example.zip](https://github.com/BHoM/BHoM/files/6004402/example.zip)

**Comment by tg359** [comment]
And here's a CSV containing a years' worth of hourly values just in case that's useful too:

[example (2).zip](https://github.com/BHoM/BHoM/files/6004425/example.2.zip)

**Comment by enarhi** [comment]
Analysis grids should also have the option to specify an orientation for the grid as part of this update.
