### ISSUE TITLE
Spatial_oM: TaperedProfile has two constructors, one of which has much less error checking

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/BHoM#1220]
#### Description:

More accurately, there are three constructors for TaperedProfile, one in the oM, and two in the Engine. The two in the Engine check that the interpolationOrder is greater than zero, though if the check fails, a null is returned rather than any attempt to make a valid object. They do not check that the InterpolationOrder is 3 or less, which is the highest sensible value (higher order would require additional information). the one in the oM checks nothing.

#### Expected behaviour:

remove superfluous constructors and provide additional error handling (and possibly documentation) for interpolationOrder

**Comment by FraserGreenroyd** [comment]
The `TaperedProfile` object is `IImmutable` so it requires a constructor for internal use. Any toolkits using it would be advised to go via the the create methods I would imagine.

**Comment by JosefTaylor** [comment]
Thanks @FraserGreenroyd, all is understood!
