### ISSUE TITLE
Facade_oM: Extrusion Bounding Box Fragment

### ISSUE THREAD

**Issue by vgreen-BH** [BHoM/BHoM#1233]
#### Description:
A fragment which contains a bounding box as a curve. The bounding box curve geometry will be included with each new mullion profile added to the facade dataset. All mullion geometry within the bounding box will be extruded when altering mullion depth from the original geometry.

**Comment by vgreen-BH** [comment]
Variations in mullion depth will be addressed by #1245 which adds the bounding box as a FrameEdgeProperty

**Comment by enarhi** [comment]
Reopening as we will begin with fragments and migrate to a property on FrameEdgeProperty if we see a need later.
