### ISSUE TITLE
Structure_oM: Adding of ReinforcementDensity and RequiredArea classes

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/BHoM#1239]
#### Description:

First two representations of rebar within the BHoM at the lowest level.

1. Reinforcement density
- Makes use of the existing `Fragments` as it's just storing a single number below
- These are owned by the `Bar` or the `IAreaElement` 
- Being a `Fragment` it can also be mapped to `Physical` elements if required for BIM software

2. Required area
- As discussed, a result class - this allows us to make use of the existing `BarResult` and `MeshResult` classes such as internal divisions (on a `Bar`) and `Node` results on a `Mesh`
![image](https://user-images.githubusercontent.com/30078587/117946063-d9316200-b306-11eb-97fc-c825af526b98.png)

Open for discussion but I think these two align with what we discussed @pawelbaran @al-fisher @IsakNaslundBh @alelom @rwemay

**Comment by pawelbaran** [comment]
I like the reinforcement density being a fragment - I see a few possible applications making use of its flexibility:
- preliminary structural magic
- BIM & project coordination
- LCA (@michaelhoehn what do you think?)

Not 100% sure about the required area - it aligns with what we discussed on the call, but having never worked with results, I would not dare to approve nor disapprove with confidence. I guess good to hear @IsakNaslundBh's opinion on that.

One question @peterjamesnugent - did you consider how would the information flow between the two representations, and further down the detail hierarchy (to layouts)? I see the two main scenarios:
- density is assigned by an engineer based on a raw estimate, without any calcs (siloed information, never to go downstream)
- required area is calculated by an engineer, then can be pushed upstream (translated into density) or downstream (translated into a layout of bars using the existing Engine methods for framing and similar to come for panels)

This seems to cover the standard cases, am I correct?

BTW, looping @LMarkowski in.

**Comment by peterjamesnugent** [comment]
> One question @peterjamesnugent - did you consider how would the information flow between the two representations, and further down the detail hierarchy (to layouts)? I see the two main scenarios:
> - density is assigned by an engineer based on a raw estimate, without any calcs (siloed information, never to go downstream)

Given the amount of information (by having the `ReinforcementDensity` as a `Fragment`), I think we could definitely send information upstream. You know the `Length`, the `Area` of the concrete element and therefore the volume. You can determine the mass of the reinforcement and therefore its `Area`.  

- required area is calculated by an engineer, then can be pushed upstream (translated into density) or downstream (translated into a layout of bars using the existing Engine methods for framing and similar to come for panels)

Yes, so you could have an A<sub>s,min </sub> and the user provides a `BarDiameter` or `Spacing` and using the existing methods it can generate some simple layouts. We should have a dataset for preferred `BarDiameter` - I've raised an issue here: https://github.com/BHoM/BHoM_Datasets/issues/88
