### ISSUE TITLE
Implement IElementxD interface by Architecture.BuildersWork.Opening

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#1257]
#### Description:

First of all conceptually, it is a spatial object, then more practically, this will be needed for e.g. transformations etc.

**Comment by FraserGreenroyd** [comment]
Probably already on your radar @pawelbaran but don't forget to create any necessary [Engine methods](https://github.com/BHoM/documentation/wiki/IElement-required-extension-methods) as appropriate :smile:

**Comment by pawelbaran** [comment]
Good timing @FraserGreenroyd - see additional comments on https://github.com/BHoM/BHoM/pull/1258 👍
