### ISSUE TITLE
Several assemblies have root namespaces suffixed *_oM

### ISSUE THREAD

**Issue by RichardWhitfield** [BHoM/BHoM#1269]
#### Broken rules:
The following assemblies have a root namespace ending `*_oM:`

- Diffing
- Facade

This is redundant information and inconsistent with the other assemblies in the BHoM solution.

#### Suggestions to restore compliance:
Remove the `*_oM` suffix - this may/will be a breaking change for anyone using the objects though good to tidy up while still in beta.

**Comment by FraserGreenroyd** [comment]
Good spot @RichardWhitfield 😺 

@alelom , @enarhi , I've had a quick look, it looks to be the default namespace that the `csproj` has set. I'll do a proper analysis in the morning to check how much impact this might have on dependant toolkits, but if it doesn't look to be too complex then we can get a quick PR up to fix this this sprint

**Comment by RichardWhitfield** [comment]
Thanks @FraserGreenroyd, seems like we can tackle the issue of the changed namespace with a versioning json in each project as well.

**Comment by RichardWhitfield** [comment]
Sorry...one more thing...Diffing is also not in the correct root namespace either.
