### ISSUE TITLE
Graphics_oM: Vertex doesn't follow naming conventions

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM#1273]
#### Broken rules:

- The colour property is called `Color` (in AmE instead of BrE)
- If we go for https://github.com/BHoM/BHoM/issues/1271, then the object should be renamed to RenderPoint
- If we do both above, we allow the Vertex class to inherit from a [`IColourable` interface](https://github.com/BHoM/BHoM/issues/1272) common to the rest of "Render" objects

#### Suggestions to restore compliance:

- Rename `Vertex` to `RenderPoint` or `RenderVertex`
- Rename its `Color` property to `Colour`
- Make it implement [`IColourable` interface](https://github.com/BHoM/BHoM/issues/1272)

**Comment by al-fisher** [comment]
Following this comment from @pawelbaran  https://github.com/BHoM/BHoM/issues/1274#issuecomment-905526775 

>Not sure however, whether a RenderPoint can exist as an independent representation, or is it always contained within a mesh or line? 

and also our chat just now @alelom about distinction between Geometry that has colour (i.e. `RenderGeometry` or some variation of based on your latest thoughts) and "special cases" of Graphical objects that have more complex rending/gradients etc. 

Perhaps `BH.oM.Graphics.Vertex` should be renamed to `BH.oM.Graphics.RenderVertex` not `RenderPoint` ? Gives good distinction then
