### ISSUE TITLE
BHoM: Review of Material class

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#133]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
@IsakNaslundBh I would consider this issue resolved through our work with Physical/Analytical oM on discipline materials?

**Comment by IsakNaslundBh** [comment]
Can be closed as discussion had and implementation done:

https://github.com/BHoM/BHoM/issues/393
