### ISSUE TITLE
Analytical_oM: Consider removal of non-generic IResultCollection

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#1359]
#### Suggestions to restore compliance:

We currently have a generic `IResultCollection` as well as a `IResultCollection<T>`. Should investigate the usefullness of keeping the non-generic interface, or if it can be removed.

**Comment by IsakNaslundBh** [comment]
TO resolve this, should consider making the `IResultCollection<T>` covariant, this is, Making it `IResultCollection<out T>`. This would also require changing the property type from `ReadOnlyCollection` to `IReadOnlyCollection`.

![image](https://user-images.githubusercontent.com/22005920/151938006-511ec35b-7cb2-40fb-b230-78cc6f4a4675.png)


Slight downside is that the interface does not implement fetching an item by index (e.g., can not do `result.Results[i]`), but think the benefit still might outweigh, as this would mean you could write a non-generic method `MyMethod(IResultCollection<IResult> resultCollection)` that then would accept any type of result collection, over having to do `MyMethod<T>(IResultCollection<T> resultCollection) where T : IResult` when targeting the generic type.

@alelom @FraserGreenroyd @al-fisher thoughts?

**Comment by alelom** [comment]
Thanks @IsakNaslundBh for this. I agree that this solution can be helpful. Worth drafing a prototype PR that I can have a look at - agreed that the benefits can outweigh the small cons.

**Comment by IsakNaslundBh** [comment]
> Thanks @IsakNaslundBh for this. I agree that this solution can be helpful. Worth drafing a prototype PR that I can have a look at - agreed that the benefits can outweigh the small cons.

Thanks @alelom . Yes, happy to open a draft PR as soon as https://github.com/BHoM/BHoM/pull/1358 has been reviewed and merged 😄
