### ISSUE TITLE
Availability of Civil3D and OpenRoads/OpenRails toolkits

### ISSUE THREAD

**Issue by cesarecaoduro** [BHoM/BHoM#1373]
As mentioned in the object, is there any opportunity to see civil connectors?
More than happy to be involved...
Cheers

**Comment by FraserGreenroyd** [comment]
Hi @cesarecaoduro 

There isn't anything in the core BHoM but I have just included [a Civil3D_Toolkit](https://github.com/BHoM/Civil3D_Toolkit) which contains the beginnings of Civil objects. Unfortunately there isn't a lot there, we haven't had a lot of scope to push this further within the BHoM space. It would be great if you would like to get involved and help develop this further with the interoperability between the BHoM and Civil3D or other Civils related toolkits.

I'd be happy to have a chat to go through the toolkit as it currently stands or provide some support to help get started if that would be beneficial? 😄

**Comment by cesarecaoduro** [comment]
Nice, I will start cloning the Civil3D toolkit to investigate how to contribute to that!
It is already a starting point ;)

**Comment by CJAndrew84** [comment]
@cesarecaoduro did you manage to get anywhere with this?

**Comment by cesarecaoduro** [comment]
Not really, I still need to get my head around how the BHoM can fit our workflows.
I can't see object models specifically oriented to the linear infrastructure geometries in the current version and we have already started this process long time ago. 
I was thinking there was already a data structure that I could leverage but it seems that I would need to start from scratch to implement it. Maybe I am wring, but I don't see definitions for civil entities (alignments, profiles, transitions, cant, superelevation, etc.) and I don't want to dump down complex elements to simple polycurve or nurbs because they are not.
What I have been working on, is a series of object classes to clearly define those elements. Question is if I should sit down and move everything across the BHoM? At this stage I think this will eventually slow down my development, as I don't fully control how the BHoM evolves.
I am happy to have a separate chat to show you what I have done so far, and maybe we can decide how to move forward. Feel free to email me separately.
Thanks!
