### ISSUE TITLE
Structure_oM: Metal Deck - object maker

### ISSUE THREAD

**Issue by ajensen19** [BHoM/BHoM#1464]
#### Description:
Based on our conversation a few mins ago I think we need a metal deck object like this that allows modelled areas to play nicely with the mass based EPD we are working with from EC3. The conversion field will be a user input field that corrects for the mass per area to allow this method to capture any possible metal deck design.
![metaldeck maker](https://user-images.githubusercontent.com/19961672/109569265-2945aa00-7ab6-11eb-9b61-3474d8096075.jpg)

**Comment by IsakNaslundBh** [comment]
Think this can be closed as of https://github.com/BHoM/BHoM/pull/1388

@michaelhoehn please feel free to reopen if you disagree
