### ISSUE TITLE
Base_oM: Create `IContainer` interface

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM#1466]
#### Description:

As discussed with @IsakNaslundBh and @al-fisher, we need a new container interface to indicate classes that can contain several related objects bundled together whilst keeping them in separate properties. This will allow to define what are classically referred to as "models", i.e. sets of objects that are interrelated, e.g. representing a building, without imposing any requirement on the individual objects to coexist in the container.

This will allow to avoid the following kind of situations:
![image](https://user-images.githubusercontent.com/6352844/214553624-ebead9cc-1107-42a0-ba44-08eb4230b2fa.png)

by replacing the "explode" with a BHoM_Engine method that "unpacks" the container and its properties in a flat list of objects. With reference to the picture, the `FEMmodel` should be an `IContainer` and should be unpackable via an `Unpack()` method, whose call can then be embedded in the BHoM_Adapter or other contexts.

**Comment by al-fisher** [comment]
Yes - perfect @alelom. 
As discussed reserving the term "model" to be inclusive of the broader definition of model which is both a collection of elements, _plus_ the means to evaluate or make predictions using those elements. i.e. a "mathematical model" or an "analysis model"


Perhaps something like:
> 

> IModel 
> - A set of compatible Objects and Specifications
> - With the means to evaluate the Properties encoded in the Specification
> - Requirement for Engine methods or Analysis to be available etc. 
> - Excepting of the trivial example of specification authored directly against defining properties.

Popping notes here for record - can pick this is up and discuss further as needed to implement `IModel` interface at a later date - that may then implement this new `IContainer` (or own an `IContainer`)

**Comment by al-fisher** [comment]
@pawelbaran @peterjamesnugent @Martian42 ☝️ ☝️ 
Origin of the `IContainer` interface
