### ISSUE TITLE
Base_oM: Add parameter for if the input parameter should be UI enabled or not

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#1482]
#### Description:

From discussions with @al-fisher @alelom .Addition of a control on the InputAttribute if a input should be made available in the UI or not.

Could be added as an enum with Enabled, Disabled as options, with default value of Enabled.

One use case that this could help resolve is in the Geometry_Engine, where an addition of a boolean input, like "skipChecks"

could be added, to bypass all the checks required for the method to function in isolation.

![image](https://user-images.githubusercontent.com/22005920/220627473-9ffa4ec2-a1c5-4bb6-b342-4292beedf4af.png)

Example above for the Normal method for polylines, which can be called several times by other methods (such as BooleanIntersection and alike).

By inclusion of the boolean argument, one can explicitly tell the method to bypass all the checks (that sometimes can be more computationally expensive than the actual method) if the code already has preformed all checks required at a previous stage.

With the addition of the property to the InputArgument, one can then default autohide this input parameter from the UI, making it so that checks are always run, and avoiding the potentially confusing boolean input argument to be put on the components.

When this is added, should also add a new compliance check, that if the exposure is set to Disabled (name for enum and property name pending), the corresponding input argument needs to have a default value.

@FraserGreenroyd happy for any thoughts.

Happy to make a first implementation of this from my end.

**Comment by FraserGreenroyd** [comment]
Have discussed with @IsakNaslundBh offline - I'm in agreement with the desire and execution, my concerns are on the planning and knock on effect to the UIs, so I'm proposing the work be split up into discrete tasks, whereby the object is changed first in advance of any UI changes, allowing each bit of work to be small in scope and easier to review.

**Comment by al-fisher** [comment]
Sounds good!

**Comment by pawelbaran** [comment]
Happy to see this happening - strongly supportive of the idea too 👍
