### ISSUE TITLE
BHoM defunct slack link

### ISSUE THREAD

**Issue by EKAdebo** [BHoM/BHoM#1494]
#### What is missing/incorrect?

Slack link on the BHoM documentation is no longer active. https://github.com/BHoM/BHoM/blob/main/CONTRIBUTING.md

**Comment by al-fisher** [comment]
Ah - gosh - thankyou @EKAdebo 

These should be removed and replaced with a links to the GitHub Discussions https://github.com/orgs/BHoM/discussions
