### ISSUE TITLE
BHoM: Legacy attributes could be deleted?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#1544]
#### Description:
During today's session with @adecler we found out that the following attributes are not used anywhere:
- [`AbbreviationAttribute`](https://github.com/BHoM/BHoM/blob/develop/BHoM/Attributes/AbbreviationAttribute.cs)
- [`AssemblyUrlAttribute`](https://github.com/BHoM/BHoM/blob/develop/BHoM/Attributes/AssemblyUrlAttribute.cs)
- [`ReleasedAttribute`](https://github.com/BHoM/BHoM/blob/develop/BHoM/Attributes/ReleasedAttribute.cs)

I believe they could be removed, but happy to wait for the green light from the originator (@al-fisher).

**Comment by al-fisher** [comment]
Happy to action this - thanks @pawelbaran 
The only one of those that would be in my mind still be desired as part of a longer roadmap for improving documentation and readability of the code would be the `AbbreviationAttribute`. This can naturally be reinstated when and if it is actually wanted to be used - so happy for the tidy up.

**Comment by pawelbaran** [comment]
Good point, I would also consider using `DisplayTextAttribute` - depends on whether you simply want to show a different value in general or only in abbreviation context.

**Comment by al-fisher** [comment]
Ah - so I see this as an specific case for Abbreviation - i.e. "EPD" for Environmental Product Declaration say or "E" for Young's Modulus. 

And you might want/need both. i.e. for Young's Modulus you can use the `DisplayTextAttribute` to put the apostrophe in. (As the Property/Quantity name will be `YoungsModulus`). And then `AbbreviationAttribute` to set as "E" naturally.
