### ISSUE TITLE
Analytical_oM: Add cutom results class

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#165]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
@IsakNaslundBh , have titled this in the `Analytical_oM` section. Feel free to correct if you disagree. If it covers many projects, you can use `Global:`. If it's only over a couple of projects, you can use `/` to separate.

**Comment by IsakNaslundBh** [comment]
DO not think this is relevant any longer. If it will be, can be reopened as new issue with more info.

Closing for now
