### ISSUE TITLE
Geometry_oM: Grids - Multi-segment not coming through

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM#192]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by pawelbaran** [comment]
Multisegment grids are supported now, so the issue is not relevant any more.
