### ISSUE TITLE
Geometry_oM: Nurb surface properties need updating

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM#226]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by al-fisher** [comment]
Closing this historic issue as a large amount of refactoring/development of our approach to NURBS handling has occurred since originally raising
