### ISSUE TITLE
Structure_oM: PanelPlanar should carry the information whether it is a wall or a floor

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#256]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by al-fisher** [comment]
I think this issue as stated here should be closed as inactive and thus legacy now. 

However the concept of analytical representations (i.e. Panels or similar) being able to have reference to other (say Physical or Analytical) representations that they are either generated from or a representation of is still a valid and useful concern.
Will likely not be solved in the individual analytical types directly themselves so will be good to close this and refer to a parent issue relating to the transdisciplinary knowledge graph work we have been discussing recently. 
@alelom @IsakNaslundBh I couldn't immediately find a place to do that - so perhaps one to capture in our planning for coming milestones and further documentation of analytical namespaces etc.

**Comment by FraserGreenroyd** [comment]
Taking note from @al-fisher comment above, and reviewing historic issues, I'm closing this issue as stale as suggested above and following no further input in the last year. If this needs revisiting, please feel free to reopen :smile:
