### ISSUE TITLE
BHoM: Adding Id's/Objects property to the filterquery

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#260]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
Closing this issue since clashing with more recent discussions where it was agreed that `FilterQuery` should be kept to its simplest form and the `Equalities` property should be removed
