### ISSUE TITLE
Environment_oM: Space - Prioritised properties

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#284]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
This has been captured within our Fragments. Ongoing changes can be raised as new issues :smile:
