### ISSUE TITLE
Data_oM: DataManipulation - Should FilterRequest implement IBHoMObject interface?

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/BHoM#286]
Filter Query is exposed to Dynamo_Toolkit, Grasshopper_Toolkit so we should be able to Shallow clone these objects:

IBHoMObject GetShallowClone(bool newGuid = false);

Thanks of that it would be easier to implement Modify methods for FilterQuery

**Comment by adecler** [comment]
`ShallowClone` now works on any object
