### ISSUE TITLE
Environment_oM Building Location change

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM#291]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
This issue is no longer relevant as `Building` class no longer contains `Location` of point or geographic.
