### ISSUE TITLE
BHoM: Add support for ECS to the base BHoMObject

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM#293]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
Following discussion with @al-fisher today, below is an example diagram showing how we could implement some extended properties within the BHoM framework. @adecler this is for you to review :smile:

I have (well, will have by the time you read this @adecler ) made a start at implementing this in Base_oM and Environment_oM for people to begin reviewing, etc. and showing how changes to the `BHoMObject` might look going for this implementation.

![image](https://user-images.githubusercontent.com/18049174/51688946-888a8380-1fed-11e9-89fb-33051ee761be.png)

**Comment by al-fisher** [comment]
Documenting plan to progress:

In addition to the initial work on Humans and now Environmental Extended properties - agreed Material will be the next candidate to implement ECS-like concepts such that we have three strong ECS prototypes before then hopefully agreeing approach to generalising 

See https://github.com/BHoM/BHoM/issues/399 & https://github.com/BHoM/BHoM/issues/393 

@IsakNaslundBh to lead materials development.

**Comment by al-fisher** [comment]
@adecler @IsakNaslundBh @FraserGreenroyd  
btw `Fragment` suggested as a name for the modular Extended Properties on an object by @rwemay - kind of liking this - works to capture the concept of properties working in isolation in parts, but can be combined to create a greater whole.

**Comment by al-fisher** [comment]
Prototyping of `IBHoMFragment` carried out in the BH.oM.Environment.Properties namespace as part of Environment refactoring PR: https://github.com/BHoM/BHoM/pull/458

**Comment by FraserGreenroyd** [comment]
@al-fisher @adecler with Fragments now added to the base BHoMObject and all objects can now have fragments (albeit they now need fleshing out in disciplines and have other tasks associated to them raised by @IsakNaslundBh ), does that mean this issue is now complete? If not, what would be the remaining steps for the completion of this issue (for clarity)? :smile:
