### ISSUE TITLE
BHoM : Add perimeter curve to BH.oM.Environment.Elements.Space

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#299]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by rboulton-BH** [comment]
I think it's related to this issue... It would be really useful to have some geometrical representation of Space elements. Fundamentally this should be a 2D perimeter curve (as is currently available for BH.oM.Architecture.Elements.Room) but could additionally include 3D volume. @MajaLindroth & @FraserGreenroyd , can you please take a look?

**Comment by BingWangUS** [comment]
I agree on having a 3D volume representation but think need to be careful not to touch too much curvature surface. Maybe we can start with simple ones as perimeter * height as @rboulton-BH suggested?

**Comment by FraserGreenroyd** [comment]
Following discussions this will now be to add a 2d perimeter curve and associated engine methods. Have updated title to reflect this.
