### ISSUE TITLE
BHoM: Consider Lazy initialisation of BHoMObject Properties like Guid

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#303]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
I think this is as a good time as any to pick this up. I think we can easily agree that changing the type of the `BHoM_Guid` property from Guid to Lazy<Guid> would be a bit of a mess right now though.

I tried this change on the BHoM_Object:

```
public Guid BHoM_Guid {
    get
    {
        if (m_BHoMId == Guid.Empty)
            m_BHoMId = Guid.NewGuid();
        return m_BHoMId;
    }
    set
    {
        m_BHoMId = value;
    }
}
```

But I barely noticed any difference in the computational time took to create a million Nodes

**Comment by adecler** [comment]
Based on lack of gain in computational time and recent work on Guid, I suggest we close this. Feel free to reopen if you disagree.
