### ISSUE TITLE
BHoM: Change Properties namespaces to include the element they refer to

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM#307]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment]
This is done on structures side:

https://github.com/BHoM/BHoM/issues/248

**Comment by FraserGreenroyd** [comment]
Happy to be closed from Environments side :smile:
