### ISSUE TITLE
Environment_oM:  Modify enum BuildingElementType

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM#338]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
To include existing enums as well for the instances where we do not know whether a `wall` is `internal` or `external`
