### ISSUE TITLE
Environment_oM: Move MaterialType into MaterialProperties

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM#383]
As per our discussion we will move MaterialType into MaterialProperties

public MaterialType MaterialType { get; set; } = MaterialType.Undefined;

@ZiolkowskiJakub @FraserGreenroyd

**Comment by FraserGreenroyd** [comment]
With the changes to extended properties and pull/push of data from Revit, this is no longer relevant. Also, we need to now await to see what @IsakNaslundBh does with materials from an ECS point of view before making too many changes to our materials for the time being.
