### ISSUE TITLE
Architecture_oM: Add Rooms

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM#389]
To follow Envbironment_oM spaces approach we will create object for Architects  - `Rooms`, 

-  Name + Number, same as space
- Point Location 
- Occupancy

**Comment by michaldengusiak** [comment]
@FraserGreenroyd  
ok we will this now for our Topologic workflow

**Comment by FraserGreenroyd** [comment]
@michaldengusiak is this an architectural room, or a physical room? Just to make sure it goes in the right oM, because if it's physical then might be worth looping @IsakNaslundBh in briefly to align requirements, but if architectural then should be fine.

What capacity will this bring to our workflow from topologic that is not available by using Environment Space?

**Comment by michaldengusiak** [comment]
@FraserGreenroyd @al-fisher 
It will be Architectural Room. You are right we might use both. This is just making more refine split and adding extra flexibility. So when we ultimately pull from Architect model we just take Rooms and Physical panels and as results we will have BHoM.Space. At the moment we were starting with spaces and ended with spaces but this will allow more flexible and elegant way.

**Comment by al-fisher** [comment]
Yes - what @michaldengusiak said above. _One_ powerful workflow will be the `Analytical.Space` being an output from `Physical.Walls` and `Architectural.Rooms`
@kayleighhoude one for you also following recent discussions

**Comment by FraserGreenroyd** [comment]
Following discussion with @kayleighhoude and others this afternoon, we should get a `Room` object into Architecture_oM to begin prototyping up this workflow ASAP.

The `Room` object should, as its basis at this stage, should contain a `Polyline` representing the perimeter of the floor of the `Room`.

This may feed into Environment `Space` stuff later, further discussions with @kayleighhoude and others will be necessary on consolidating that.

Action for now:

 - Create `Room` object with a `Polyline` perimeter boundary to be pulled by Revit_Toolkit/Others.
