### ISSUE TITLE
Global : Update links in Readmes 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#412]
With latest formalising of governance and deployment strategy - a number of links to update in READMEs.

- [ ] Link to installer - create new bhom.xyz/installer page to link to such that link can be be static and constant for each deployment @epignatelli - to action in https://github.com/BHoM/bhom.github.io 
- [ ] Add link to newly merged CODE_OF_CONDUCT
- [ ] Add link to newly merged GOVERNANCE

**Comment by FraserGreenroyd** [comment]
ReadMe's were reformatted after this issue was raised and currently meet the new standards.
