### ISSUE TITLE
Environment_oM: Material roughness

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM#417]
Materials should also specify their roughness in addition to a construction roughness. This is to be looked at in either March or April sprints pending the outcome of other material refactoring.

**Comment by tg359** [comment]
I'm distracting myself from work to suggest we only specify roughness for `Material`s, and not `Construction`s - as the `Roughness` of a construction (which is a set of layered `Material`s) differs based on the exposed/visible material. For instance, a wall made of [`Plasterboard` | `Insulation` | `Air` | `Brick`] would be smoother on one side than the other. We should have a method of determining Construction roughenss based on the visible surface material and viewing vector.

This would link well with the definition for `Material` currently in the data schema being defined for BuildingEnvironment_Toolkit [here](https://github.com/BuroHappoldEngineering/BuildingEnvironments_Toolkit/blob/BEnv_Toolkit-Issue156-DataSchemaDefinition/DataSchemata/Materials/OpaqueMaterial.json).

**Comment by FraserGreenroyd** [comment]
This will be resolved as part of #457 .
