### ISSUE TITLE
Geometry_oM: Add 3D mesh object

### ISSUE THREAD

**Issue by tg359** [BHoM/BHoM#419]
We've currently got the ability to handle a 2D mesh described by vertices and faces, but in Building Environments we deal mostly with 3D volumetric meshes. The simplest of which would be a single cell (the simplest being a "_tet_", with 4 triangular faces), with some way of relating the vertices, faces, and the volume being defined. 

We need a 3D mesh object to be defined to support the volumetric meshing of buildings/external spaces for 3D daylighting and CFD applications.

A really good example of this is for OpenFOAM CFD which has robust meshing in its `blockMesh` and `snappyHexMesh` programs. These would generate a composite mesh from a set of files defining:
- points (the 3DPoint)
- faces (a face defined by 3+ 3DPoints)
- owner (the cell ID which _owns_ the individual faces)
- neighbor (the neighboring face for each mesh cell (I think, I'm not too sure on that one))
- boundary (a collection of faces - for assignment of boundary conditions)

The files [here](https://github.com/BHoM/BHoM/files/2893932/OpenFOAM_mesh.zip) define the mesh shown below:

![image](https://user-images.githubusercontent.com/10939984/53242783-b66ef080-369d-11e9-9818-258e2d2a2e45.png)
@EwanFrench tagged for visibility.

**Comment by EwanFrench** [comment]
The manipulation of the meshes are really important as well - Rhino has its own ways of smoothing or simplifying for example but these could render the mesh entirely unusable in Openfoam so if we could check or smooth meshes in Rhino (or other programmes for visualisation) using Openfoam methods that'd be amazing!

Best,

Ewan

**Comment by tg359** [comment]
Just for fun, here's an example of `checkMesh` run on the one shown above:

```
/*---------------------------------------------------------------------------*\
| =========                 |                                                 |
| \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\    /   O peration     | Version:  5.x                                   |
|   \\  /    A nd           | Web:      www.OpenFOAM.org                      |
|    \\/     M anipulation  |                                                 |
\*---------------------------------------------------------------------------*/
/*   Windows 32 and 64 bit porting by blueCAPE: http://www.bluecape.com.pt   *\
|  Based on Windows porting (2.0.x v4) by Symscape: http://www.symscape.com   |
\*---------------------------------------------------------------------------*/
Build  : 5.x-963176928289
Exec   : C:/Users/tgerrish/AppData/Roaming/BLUECF~1/OpenFOAM-5.x/platforms/mingw_w64GccDPInt32Opt/bin/checkMesh.exe
Date   : Feb 22 2019
Time   : 12:56:26
Host   : "BTH-PF0VA3EQ"
PID    : 3632
I/O    : uncollated
Case   : C:/Users/tgerrish/AppData/Roaming/BLUECF~1/ofuser-of5/run/cavity
nProcs : 1
SigFpe : Enabling floating point exception trapping (FOAM_SIGFPE).
fileModificationChecking : Monitoring run-time modified files using timeStampMaster (fileModificationSkew 10)
allowSystemOperations : Allowing user-supplied system call operations

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Create time

Create polyMesh for time = 0

Time = 0

Mesh stats
    points:           882
    internal points:  0
    faces:            1640
    internal faces:   760
    cells:            400
    faces per cell:   6
    boundary patches: 3
    point zones:      0
    face zones:       0
    cell zones:       0

Overall number of cells of each type:
    hexahedra:     400
    prisms:        0
    wedges:        0
    pyramids:      0
    tet wedges:    0
    tetrahedra:    0
    polyhedra:     0

Checking topology...
    Boundary definition OK.
    Cell to face addressing OK.
    Point usage OK.
    Upper triangular ordering OK.
    Face vertices OK.
    Number of regions: 1 (OK).

Checking patch topology for multiply connected surfaces...
    Patch               Faces    Points   Surface topology
    movingWall          20       42       ok (non-closed singly connected)
    fixedWalls          60       122      ok (non-closed singly connected)
    frontAndBack        800      882      ok (non-closed singly connected)

Checking geometry...
    Overall domain bounding box (0 0 0) (0.1 0.1 0.01)
    Mesh has 2 geometric (non-empty/wedge) directions (1 1 0)
    Mesh has 2 solution (non-empty) directions (1 1 0)
    All edges aligned with or perpendicular to non-empty directions.
    Boundary openness (8.47033e-018 -8.47033e-018 -4.51751e-017) OK.
    Max cell openness = 1.35525e-016 OK.
    Max aspect ratio = 1 OK.
    Minimum face area = 2.5e-005. Maximum face area = 5e-005.  Face area magnitudes OK.
    Min volume = 2.5e-007. Max volume = 2.5e-007.  Total volume = 0.0001.  Cell volumes OK.
    Mesh non-orthogonality Max: 0 average: 0
    Non-orthogonality check OK.
    Face pyramids OK.
    Max skewness = 1.66533e-014 OK.
    Coupled point location match (average 0) OK.

Mesh OK.
```

**Comment by kThorsager** [comment]
This has been open for a while and Environments seem to still be working,

Is this still requested and needed?
Sounds very interesting, but I'm assuming you've created some workaround, so let me know how you want this to proceed @tg359

**Comment by FraserGreenroyd** [comment]
This would be good to include still @kThorsager as the workaround has been to not continue with the work that needed this. This was about unlocking capacity to do more complex environments work which has been on hold for a while - so if it can be included still it would be good please.

**Comment by BingWangUS** [comment]
I second the importance of a rectangular mesh. Recently trying to visualise Harpoon mesh result in Rhino, used STL as a interface, but created a wrong information because STL split the rectangle to triangle. Sorry for being late to this thread.
