### ISSUE TITLE
Geometry_oM: Add IElement2D to ICurve and PlanarSurface

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#426]
the IElement2D interface could be added to PlanarSurface, but to be able to extract internal openings, the same will be needed for ICurve.

Not doing this as part of https://github.com/BHoM/BHoM/issues/424 as needs to be verified as correct strategy.

**Comment by pawelbaran** [comment]
After giving it a thought, I would say it might be a tricky precedence to implement the `IElement2D` by `ICurve` as it will become both `IElement1D` and `IElement2D` at the same time. As long is might be considered sensible in case of a Polyline or PolyCurve, it does not make any sense for a Line. Maybe the PlanarSurface could use PolyCurves as its internal & external outlines?

**Comment by IsakNaslundBh** [comment]
Would prefer to keep it as `ICurve` to be able to use `Polylines` as well as `Circle`/`Ellipse`. That was at least my reason to go with ICurve over Polycurve. Also think all of these curve types could have skope to be considered IElement2D.

Could potentially also work around this in the engine in a different way, by slightly modifying some of the methods etc.

**Comment by pawelbaran** [comment]
Yeah, got your point about an `ICurve`, but the current architecture will make it problematic to implement `IElement2D` in a fully sensible way, as explained above.
An alternative could be to wrap `Circle`, `Polyline`, `Ellipse` etc. into a `PolyCurve` with 1 item in its `Curves` property. Similar is being done in DistributeOutlines, e.g. once you have a panel with a round opening.

**Comment by kThorsager** [comment]
Not sure if still on the agenda,
But if we let #789 cast circle etc to `PolyCurve` and and start enforcing more rigours checks on the closeness of `IElement2D`s (there are currently non, and the methods assume that they are) I could see this as an interesting feature.

The `PlanareSurface` as `IElement2D` is good regardless at this point

**Comment by IsakNaslundBh** [comment]
Had another think and discussion about this yesterday, and will aim to close this out next sprint.

The reason this has not already been done (adding the IELement2D itnerface to the PlanarSurface) is that we had no strategy for extracting the openings in a way that fits the requirements (being able to return a list of InternalIElement2Ds). Strategy for this will be to create a a set of new temporary PLanarSurfaces that correspond to the openings, i.e. new PLanarSurfaces that have external boundaries matching the InternalBoundaries of the host planar surface.

This way this issue can be resolved without the need to interfere with the curve classes.
