### ISSUE TITLE
Architecture_oM: Add Window, Door

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM#433]
We need to add Windows and Doors to have required environmental physical elements and be able to generate full model. 

for example from revit side will be needed to push:
Window - Window, Rooflight, System Panel
Door - internal, external doors

**Comment by FraserGreenroyd** [comment]
Can this be included on your diagrams from Revit/TAS, etc. for @IsakNaslundBh and I to consider when we meet to discuss the physical and analytical elements in a couple of weeks. Cheers.

**Comment by al-fisher** [comment]
Yes please! Thanks @michaldengusiak @FraserGreenroyd

**Comment by FraserGreenroyd** [comment]
I am considering this issue closed through the merge of the Physical oM. If the oM does not meet the requirements listed here please relist the requirements as required.
