### ISSUE TITLE
Reflection_oM: Add attribute to not expose a method in the UI

### ISSUE THREAD

**Issue by epignatelli** [BHoM/BHoM#439]
We usually aim at transparency between what we code in visual studio and all the available components in the UI, i.e. every method that is coded in the Engine is exposed as a component in the UI.

This connection can be broken by making the method `private`, but this is not always a convenient choice, since it affects its accessibility at developer level too.

To get the best from both of them, we resort to `Attribute`s. An attribute like `[NotExposed]` would be a good trade off to have a method implemented but not exposed to the UI.

**Comment by FraserGreenroyd** [comment]
I would concur with something like this, as I have a lot of methods in my engine which are helpful from a development point of view in the toolkits but not so helpful on the UI. Having the ability to choose not to expose all the methods would be very welcome to me!

**Comment by epignatelli** [comment]
Cool! But I think the argument is not about how helpful they are, but how harmful they can be. like crashing, invalidating and so on.

**Comment by epignatelli** [comment]
Closing because the `Attribute` will not be implemented. For further details you can refer to https://github.com/BHoM/BHoM/pull/662
