### ISSUE TITLE
Physical_oM: Create Surface class

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM#441]
After #440 

Create a `Surface` object with abstract `Wall`, `Floor`, and `Roof` objects as abstract classes as one-line definitions within the same file.

`Surface` object should contain the following properties (names TBC):
 - `ISurface` defining the outer edge geometry called `OuterBoundaries`
 - `IConstruction` defining the look/feel of the panel called `Construction`
 - Collection of `IOpening` defining the inner holes of the panel called `Openings`
- `Offset` defining the location of the geometry in relation to its edge - outer edge, inner edge, centre, etc. Currently to be called `Offset`

**Comment by IsakNaslundBh** [comment]
Edited name and comments from panel to surface
