### ISSUE TITLE
Geometry_oM: Add Basis class

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#448]
Additional `Basis` class to be added to Geometry_oM.

Class to contain three vectors, forming a Vector space. Similar to Coordinatesystem, but without any origin.

To be used on results etc, where no positional information should be given.

**Comment by pawelbaran** [comment]
Just out of curiosity: wouldn't CoordinateSystem.Cartesian with a null origin be fine?

**Comment by IsakNaslundBh** [comment]
I don't think so. They imply different things.

The two examples of usage so far will be on the node (splitting it away, making the node own a point again as well as a basis instead of a coordinate system) and on the mesh and node results, where any positional information should be carried by the elements, not the results. Having a coordinate system with a null origin sends a completely different message I think.

**Comment by pawelbaran** [comment]
Got it 👍
