### ISSUE TITLE
Structure_oM: Migrate ShapeProfiles to Geometry_oM

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#480]
Migrate the ShapeProfiles to Geometry oM to be able to use from other projects such as Environments and physical.

**Comment by al-fisher** [comment]
Noting as discussed with @IsakNaslundBh the `ISectionProperty` and implementations of will remain discipline specific with additional Analytical Constants. 
A discipline `SectionProperty` being a composite of a geometrical _Shape Profile_ and dependant _Section Constants_
