### ISSUE TITLE
Environment_oM: Tidy materials

### ISSUE THREAD

**Issue by tg359** [BHoM/BHoM#484]
Further to @FraserGreenroyd changes to Environment_oM this tidy up to materials is needed.

This includes:

 - Environment_oM/Fragments/EnvironmentConstructionFragment.cs < Add AdditionalHeatTransfer
 - Environment_oM/MaterialFragments/Absorptance.cs < Remove Absorptance (the file not the attribute)
 - Environment_oM/MaterialFragments/GasMaterial.cs < Remove Absorptance and AdditionalHeatTransfer
 - Environment_oM/MaterialFragments/IEnvironmentMaterial.cs < Remove Absorptance and AdditionalHeatTransfer
 - Environment_oM/MaterialFragments/SolidMaterial.cs < Remove Absorptance and AdditionalHeatTransfer

**Comment by tg359** [comment]
Yet more additions to make, this time for the visual appearance of a material! And [here] (https://www.sabic-ip.com/cxp/jsp/user/LearnAboutColor/ColorBasicsDetail/refractive_indices.jsp)is a REALLY useful site detailing what all of these mean, and [HERE](http://www.artifice.com/radiance/radmatlib.html) is a materials dataset containing a bunch of these predefined that we could map to our materials.

**Reflectance**
- Fraction of reflectivity [0-1]
- Applied to opaque/semi-transparent materials
- Split between _RedReflectance_, _GreenReflectance_ and _BlueReflectance_ fractions (for different wavelengths of light individually)

**Transmittance**
- Fraction of light transmitted [0-1]
- Applied to transparent materials
- Split between _RedTransmittance_, _GreenTransmittance_ and _BlueTransmittance_ fractions (for different wavelengths of light individually)

**Specularity:**
- Fraction of [specularity ](https://en.wikipedia.org/wiki/Specularity)[0-1]
- Specularity helps defines the direct reflection component of reflectivity (why you'd get glare-y spots on a shiny material, but not a matt material)
![image](https://user-images.githubusercontent.com/10939984/57914945-9ce9d900-7887-11e9-817b-4b1ba272d336.png)
- Specularity fractions greater than 0.1 are not realistic for smooth materials (default: 0)
- Specularity of metals is usually 0.9 or greater (default: 0.9).

**Refraction**
- The [refractive index](https://en.wikipedia.org/wiki/Refractive_index) of the material
<img src="https://user-images.githubusercontent.com/10939984/57915300-5fd21680-7888-11e9-8805-ecf4fdf89813.png" width="300">

**Roughness:**
- Roughness is specified as the rms slope of surface facets. A value of 0 corresponds to a perfectly smooth surface, and a value of 1 would be a very rough surface. Roughness values greater than 0.2 are not very realistic. (default: 0).

**TransmittedDiffusivity**
- Applied to translucent materials only
- The transmitted diffuse component is the fraction of transmitted light that is transmitted diffusely in as scattering fashion.

**TransmittedSpecularity**
- Applied to translucent materials only
- The transmitted specular component is the fraction of transmitted light that is not diffusely scattered

**Comment by FraserGreenroyd** [comment]
Following discussion with @tg359 the following will be implemented to resolve this issue:

 - Reflectance - an additional reflectance fragment which allows users to specify the high-accuracy reflectance values by colour, while leaving the single light/solar reflectance values currently available
 - Transmittance - as reflectance
 - Specularity - this will be a double value only available on `SolidMaterial` fragments
 - Refraction - this will be a double value available on both `Solid` and `Gas` fragments
 - Roughness - this will not be done here in the oM, this will be an engine method to map our `MaterialRoughness` enum to a numerical value
 - TransmittedDiffusivity - double value on `Solid` only
 - TransmittedSpecularity - as above
