### ISSUE TITLE
Graphics_oM : Add a Graphics.MaterialFragments.IMaterialFragment

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#485]
This can follow the work restructuring the `Physical.Materials.Material` and `MaterialFragments` in `BH.oM.Structure` and `BH.oM.Environment` 

This `Graphics.MaterialFragment` can contain material render properties, translucency models etc.

**Comment by al-fisher** [comment]
See https://github.com/BHoM/BHoM/issues/399 and associated issues in progress here: https://github.com/BHoM/BHoM/pull/481

**Comment by al-fisher** [comment]
@alelom @enarhi - this will be of interest for you with respect to Unreal_Toolkit

**Comment by enarhi** [comment]
@al-fisher agreed, as of now material handling is limited to an explicitly stated RGB, will include materials migration as part of our plugin improvements going forward.

**Comment by IsakNaslundBh** [comment]
Will tackle this in the work of enabling more/better graphical representations to be described by the BHoM. If the first atempt tackled by my PR is not covering everything required for Unreal workflows, it can always be extended in subsequent PRs 👍 

Hope that plan sounds alright to all involved here! :)

**Comment by enarhi** [comment]
Sounds good to me. Will be happy to test after the initial work to see how it translates to Unreal and the like.
