### ISSUE TITLE
Structure_oM: Add IProperty interface

### ISSUE THREAD

**Issue by rwemay** [BHoM/BHoM#486]
This would make it easier in the converts where some applications have one type of constraint (6DOF) for all/most use cases. @IsakNaslundBh thoughts?

**Comment by IsakNaslundBh** [comment]
Could add this, no real harm in doing so. Not sure how much it would help on the side of the toolkits, as you still would need to cast it to the actual type to get out its properties, but could add an empty interface and see if it is helpful!

**Comment by IsakNaslundBh** [comment]
Adding to this, Might even add an "IProperties" interface to tag all property-type obejcts in the oM. Could help filtering those out, and might be useful for things like generating standard names etc.

**Comment by IsakNaslundBh** [comment]
Renaming this issue to the suggestion from my previous comment. Will be able to make use of this for handling unnamed properties.
