### ISSUE TITLE
Analytical/Structural_oM : Rename ILink Properties to Start/End

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#487]
Rename `StartNode` `EndNode` :

``` c#
public Node Start { get; set; }

public Node End { get; set; }

```

To remove duplication of information. This approach for naming conventions needs to be documented more fully in Wiki etc.

**Comment by FraserGreenroyd** [comment]
I have documented this [here](https://bhom.xyz/documentation/BHoM_oM/#defining-properties) on the documentation as part of closing this issue out in historic issue review.
