### ISSUE TITLE
Structure_oM: Pilecap and piles

### ISSUE THREAD

**Issue by jdarcyBHE** [BHoM/BHoM#505]
I feel it would be useful to add pilecaps and piles into the oM. Below are my thoughts:

1. Pile objects are already implemented using a format matching columns. This might need to be altered to: point (top of pile), rotation angle (plan orientation for driven H piles), length, section, type (driven, bored, secant etc)

2. Pilecap parameters: pile objects, pilecap thickness, pilecap outline, top of pilecap level, material

3. My intention is to be able to push the objects into Revit, however I could see in future wanting to push into analysis and so having spring stiffness embedded into the piles would be useful as well.

I feel this could be useful on several projects at the moment, thoughts anyone?
@IsakNaslundBh @PiotrBuda  @pawelbaran @ZiolkowskiJakub @rwemay

**Comment by peterjamesnugent** [comment]
This has been addressed, see:
https://github.com/BHoM/BHoM/blob/develop/Structure_oM/Elements/Pile.cs
https://github.com/BHoM/BHoM/blob/develop/Structure_oM/Elements/PileFoundation.cs
