### ISSUE TITLE
Diffing_oM: Implementation

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM#506]
Implement Diffing_oM. This should include a `Delta` class with the [schema agreed in AECDeltas](https://github.com/aecdeltas/aec-deltas-spec/wiki/Delta-Specification):

```
+ ToCreate {get; private set;} // or "new"
+ ToDelete {get; private set;} // or "old"
+ ToUpdate {get; private set;} // or "modified"
+ ProjectId {get; private set;}
+ Version {get; private set;}
+ Timestamp {get; private set;}
+ Signature {get; private set;}
+ Sender {get; private set;}
```

### Other references
https://github.com/BHoM/BHoM_Engine/issues/1031

**Comment by epignatelli** [comment]
What about:
```
+ List<object> Created {get; private set;} 
+ List<string> Deleted {get; private set;}
+ List<string> Updated {get; private set;}
+ string ProjectId {get; private set;}
+ string Version {get; private set;}
+ long Timestamp {get; private set;}
+ string Signature {get; private set;}
+ string Author {get; private set;}
```
?

Also what is the difference between `Author` and `Signature`?

**Comment by al-fisher** [comment]
> Also what is the difference between Author and Signature?

Author is a string - Signature should be a uniquely identifiable key. There is an argument that the Author string could be derived from the other - was up for discussion actually

**Comment by al-fisher** [comment]
Also - with reference to `Created` vs `ToCreate` etc. 
@epignatelli I like your past tense actually. Makes sense in the context of a Delta being the result of an action or comparison.

**Comment by alelom** [comment]
We just had a chat with @epignatelli 

While I understand your point of view with regard to the past tense, the reasoning for me was that we have an underlying Adapter convention of calling "Created" the objects that are already exported (=Created) into an external software. We originally thought of the Diffing as a separate mechanism that should happen before that object creation phase. Let's discuss.

With regards to the signature, I agree, we could get rid of the author.

I like the fields as described by Eduardo, and as we spoke he also proposed to add another one, to which I agree:
```
+ Dictionary<string,object> CustomData {get; set}
```
that could be useful in the future for people to get more flexibility out of this standard. A simple usage example might be to add Comments to the delta.

**Comment by al-fisher** [comment]
One thing to consider would be to not use terms like "Create/d" at all and use terms closer to your "New" and "Old" above. This would actually make the Diffing much more general and applicable to not just comparing streams of data in the adapter, but two general collections or Sets of information

**Comment by alelom** [comment]
> One thing to consider would be to not use terms like "Create/d" at all and use terms closer to your "New" and "Old" above. This would actually make the Diffing much more general and applicable to not just comparing streams of data in the adapter, but two general collections or Sets of information

Personally I like this the most. I didn't think of this before, but I'd probably stay away from the `Create` description if possible. This would avoid confusion as `Create` itself corresponds to a status, which might be interpreted differently depending on the context, and I think we just want to restrict the diffing judgement to a comparison.

Just to put something else on the table, your proposal made me think about your idea of describing the two input sets only as "Set A" and "Set B" -- without qualifying them with time. This could correspond to properties such as `onlySetA`, `onlySetB`, `Intersection`. Then one could decide a convention that A is new and B is old.

**Comment by alelom** [comment]
I've since modified my definition of the [delta class](https://github.com/BHoM/BHoM/blob/Diffing_Engine-initialImplementation/Diffing_oM/Delta.cs) to include more properties that I'm using in the Diffing_Engine.

I think that this definition: 
```
+ ToCreate {get; private set;} // or "new"
+ ToDelete {get; private set;} // or "old"
+ ToUpdate {get; private set;} // or "modified"
+ ProjectId {get; private set;}
+ Version {get; private set;}
+ Timestamp {get; private set;}
+ Signature {get; private set;}
+ Sender {get; private set;}
```
represent another kind of class, I'll call it `Delta_message`, because that must contain the minimum information to be sent over the wire.

**Comment by adecler** [comment]
I like created/deleted/updated the most in term of naming convention.

The issue I have with new/old is that it can be confused with incoming/existing and so old would not necessarily be understood as something that needs to be removed. See for example [the case of meteor.js](https://docs.meteor.com/api/collections.html#Mongo-Cursor-observe) where their undertanding of new/old would clash with the one proposed here.

I would also recommend having a look at [how Mongo is handling diffing](https://docs.mongodb.com/manual/reference/change-events/#change-stream-output). There are obviously some conceptual differences with what we are doing here but some reusable ideas nonetheless.
