### ISSUE TITLE
Structure_oM: BarVaryingDistributedLoad review

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#507]
The properties DistanceFromA and DistanceFromB needs a review.

Need to specify unit (paramter 0-1 or meters), currently it is assuming meters. This need to be put in writing. Also, review needed if having distance from start and end is the right way to do it or if both values should be in reference to the starting point.

**Comment by jdarcyBHE** [comment]
I believe we should be able to do either 0-1 or metre input for distance. With regard to distancefromA and distancefromB I think it would be better changing to distanceA and distanceB where both are values from the start point.  Potentially within the method any value below 1.0 should be treated as a 0-1 parameter and above as a distance.

**Comment by rwemay** [comment]
I would definitely consider renaming all of the properties (Force A etc) to ForceAtStart, DistanceFromStart etc. If metres (default SI) then AbsoluteDistanceFromStart is OK, but if 0-1 parameter, I would suggest RelativeDistanceFromStart. These should not be able to exist together, so one might want to be an engine method/query to get/set rather than a property. 

There are cases where relative is useful/needed (a continuous relationship to the bar lengths), and where absolute is useful (a continuous relationship to another object).

**Comment by IsakNaslundBh** [comment]
To revive this a bit, suggesting we add this as a boolean/enum to the loadclasses referencing a "DistanceFrom" parameter to control this. Default could still be in meters, but you can then be able to switch it to be relative. Think this could be a simple solution to get the best of both worlds.

**Comment by IsakNaslundBh** [comment]
Updating this to a feature issue. Will add boolean property to BarVaryingDistributedLoad and BarPointLoad stating if the lengths should be in meters or in relative (between 0 and 1).

**Comment by IsakNaslundBh** [comment]
Will finally start working on this this sprint, with the following changes from above:

- Add `RelativeDistance` bool to control if the distances should be seen as relative or not
- DistanceFromA -> StartPosition. same behaviour as before except for allowing relative distance as well. Distance from the start node of the bar to the start of the load.
- DistanceFromB -> EndPosition. Change to measure distance from the start of the bar rather than distance from the end of the bar. To handle relative distance as well as distance in meters.
- ForceA -> ForceAtStart. Simple renaming, force value at the start position
- MomentA -> MomentAtStart. as above
- ForceB -> ForceAtEnd. as above
- MomentB -> MomentAtEnd. as above
