### ISSUE TITLE
Reflection_BHoM: Input and Output attributes to target constructors 

### ISSUE THREAD

**Issue by LivAndersson** [BHoM/BHoM#510]
Would be useful for Adaptors to have output and output descriptions similar to Engine methods, however, they can't be added because they don't target constructors. Can this be changed to allow them to target constructions so that documentation descriptions can be added to Adaptors?

**Comment by FraserGreenroyd** [comment]
@adecler I had a look at this with @LivAndersson and I have some template code on my machine so am happy to address this issue if you're happy with me doing so? :smile:

**Comment by adecler** [comment]
@FraserGreenroyd , I am more than happy for you to submit your code as a PR. I will never complain about someone doing the work for me :-P. Just add me as a reviewer.
