### ISSUE TITLE
Spatial_oM: add tapered flange sections

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/BHoM#512]
To allow creation of sections such as:
C - Channels with tapered flanges, slope = 2/12
MC - Channels sometimes with tapered flanges, slope != 2/12
S - H Shapes with tapered flanges
M - H shapes which are not W or S shapes (sometimes have tapered flanges)

**Comment by pawelbaran** [comment]
@JosefTaylor is this issue related to BHoM or BHoM_Engine? If latter, could you please move it accordingly? Thanks!

**Comment by JosefTaylor** [comment]
Oh good point. If tapered flanges are supported in BHoM, this should move to Engine. If tapered flanges are not supported in BHoM, this should be renamed Geometry_oM: etc. etc. and a new issue should be opened in Engine. Is that correct?

**Comment by JosefTaylor** [comment]
Checked the code, confirmed that oM does not support these sections, so this is an oM issue. When we're ready to make a related Engine issue, should it be called the same thing, in order to align and test? or do only the PRs need to have the same name?

**Comment by al-fisher** [comment]
The issue names do not need to align exactly - as long as they are meaningful.
For dependant PRs - it is only the _branch_ names that it is super critical that they match identically. This is such that our little CI Bot can find them!

**Comment by pawelbaran** [comment]
Not sure again, but shouldn't this sit in the Structure_oM as a discipline-specific item? @IsakNaslundBh @rwemay

**Comment by IsakNaslundBh** [comment]
@pawelbaran All the profiles are moved to the Geometry_oM. Need to sit there as used by both Structure_oM and Physical_oM. Also quite a few of them are generic and could be used across disciplines (CircularProfile/RectangularProfile for ducts for example).

So any addition, even if quite structures focused as in this case, should sit in the geometry_oM.
