### ISSUE TITLE
Environment_oM: Update LightingGain Properties

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM#516]
#### Description:
Add Sensible Gain property to LightingGain:
``` C#
public double SensibleGain { get; set; } = 0.0;
```
FYI @FraserGreenroyd

**Comment by FraserGreenroyd** [comment]
@kayleighhoude we currently have this on `LightingGain`: `public double Value { get; set; } = 0.0;` - I believe this is meant as the value of the gain in question, is `SensibleGain` this value (for lighting) or is `SensibleGain` a different value?

(This is the area of Environment oM which needs a lot of work so I want to better understand the variables we need in this area :smile: )

**Comment by michaldengusiak** [comment]
@kayleighhoude 
`Lighting gain` opposite to equipment that can be latent and sensible, it is always sensible, therefore we have one `value `

**Comment by FraserGreenroyd** [comment]
Actions as per discussion:

 - [ ] Delete Gain Type Enum
 - [ ] Delete Gain Unit Enum
 - [ ] Empty IGain interface
 - [ ] Delete Gain object
 - [ ] Delete IGainProperties object
 - [ ] Delete SensibleEquipmentGain object to combine into one Equipment Gain object

 - [ ] Infiltration Gain to contain sensible and latent properties
 - [ ] Equipment Gain to contain sensible and latent
 - [ ] Lighting Gain to contain sensible
 - [ ] People Gain to contain sensible and latent
 - [ ] Pollutant Gain to contain sensible and latent
