### ISSUE TITLE
Structure_oM: RigidLink Name

### ISSUE THREAD

**Issue by ChrisSelf2** [BHoM/BHoM#533]
#### Description:
RigidLink does not have a definition of a Name in the constructor. Is there a reason this has been left out? When pushing lots of these objects, the MidasCivil_Toolkit uses `BHoMObjectNameComparer`, hence a name needs to be assigned. This can be done using the `SetProperty` method, however would be easier to have it as part of the object. Can this be added?

@peterjamesnugent

**Comment by IsakNaslundBh** [comment]
Think this should/could be added. It is a Engine issue though, rather than oM. Issue opened for it here:

https://github.com/BHoM/BHoM_Engine/issues/1127
