### ISSUE TITLE
Architecture_oM : Proposing migration of Grid and Level to a common namespace

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#536]
As part of current review of namespace/discipline interdependencies keen to revisit the appropriate namespace for the `Grid` and `Level` objects.

Grids and Levels are concepts we are using widely across Toolkits.
Both of which can naturally, and will very likely be, driven and set out by Architectural requirements. However is important other namespaces have as few hard coded dependencies as possible. Thus the reason for this suggestion to migrate objects to negate the requirement for all disciplines to depend on Architecture. 

We currently have `BH.oM.Common` as a namespace although - I would ideally like us to be deprecating and migrating the remaining objects from this namespace into more appropriate. (`Material` for instance has already been ported to `BH.oM.Physical`)

As discussed with @rwemay - therefore proposing moving the  `Grid` and `Level` to `BH.oM.Geometry`

**Comment by rwemay** [comment]
👌👍

**Comment by epignatelli** [comment]
From the Sprint Closure call - Hi @al-fisher @rwemay! has this one been solved offline, or is there any plan for this to be implemented in the 2.5 sprint?

**Comment by al-fisher** [comment]
Thanks @epignatelli - yep I have some code to push on this - will do so today so can be included in compliance mop up in RC milestone

**Comment by epignatelli** [comment]
Ok! I can help reviewing to speed it up if you want!

**Comment by al-fisher** [comment]
Thanks for that @epignatelli
