### ISSUE TITLE
Should fragments be IObject instead of IBHoMObject?

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM#537]
I had a go with the fragments during the implementation of the Diffing_Engine prototype.
When doing that, I had to store a `string` -- the hash -- in my objects, for which I duly created my `HashFragment`. Therefore, to store a string, I also had to store GUID, Name, and other properties I would never make use of.

The same is true for the "AdapterId". If we want to get rid of the CustomData, then we'll need an `AdapterIdFragment` to store only the id field, but that will still force all IBHoMObject properties to be there as well -- which will probably never be put to any use.

**What about having the Fragments as `IObject` instead?**

- that would not force on the coder many properties he might not need
- nothing stops the coder to make a fragment which implements `IBHoMObject` if needed

@al-fisher @adecler @epignatelli @FraserGreenroyd @IsakNaslundBh

**Comment by adecler** [comment]
I am with you on this one. I don't see the point of having fragments as IBHoMObjects. 
On a thematic level, it doesn't make sense either: they are fragments of objects, not full BHoM objects.

**Comment by al-fisher** [comment]
Yes - agreed too - sounds good.

**Comment by alelom** [comment]
@al-fisher @adecler As agreed today I will action this in https://github.com/BHoM/BHoM/issues/563
