### ISSUE TITLE
IEquality should be removed from IRequest

### ISSUE THREAD

**Issue by alelom** [BHoM/BHoM#546]
#### Broken rules:

IEquality is a dictionary that is improperly used to make FilterRequest work for a variety of applications for which instead another type of IRequest should be implemented.

FilterRequests should be used only in BH.oM.Data and not implemented as Requests for other Adapters.

#### Suggestions to restore compliance:

IEquality should be removed from IRequest once its use is correctly removed from all places where it's now used (e.g. Revit)
Toolkits currently implementing requests as FilterRequest should create instead their own types of Request.

**Comment by adecler** [comment]
@alelom, is this still relevant ?

**Comment by alelom** [comment]
No I see it has been removed.
