### ISSUE TITLE
Physical_oM: Add OriginContextFragment

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/BHoM#553]
#### Description:

I am missing now in Physical elements some reference to the origin. Therefore I believe we should implement `Fragments` to _Physical_oM_ and as starting point add `OriginContextFragment` similar to what we have in Environment oM. I need this reference to my workflow using Physical Elements.

**Comment by rwemay** [comment]
Sorry for the silly question(!!!) but - do we need to include 'Fragment' in names like the suggested property, or can it just be 'OriginContext' and then the fact that it would inherit from IFragment is explicit enough? Just thinking of the name lengths.

**Comment by michaldengusiak** [comment]
`OriginContext` is fine with me...

**Comment by FraserGreenroyd** [comment]
We would then run the risk of having duplicate fragment objects between Environment and Physical.

What is wrong with adding the Environment Fragment onto the Physical object? The joy of the fragments as currently implemented is that any fragment which implements the `IFragment` interface can be added to any BHoM Object. So, while this discussion is ongoing, if you need to prototype up a workflow using an `OriginContext` then you can use the one in Environment oM for the time being. Especially as I would want to know from @IsakNaslundBh (or someone in his team) whether an `OriginContext` fragment is useful to them. If it is, then we need to look to migrate what is in Environment oM up to a common level, but if it isn't then there would be no need of an additional or moved fragment out of Environment oM.

This is thus something which will need careful consideration before implementation.

**Comment by rwemay** [comment]
Possibly useful as a general/high level concept - again sorry for the silly question, but presumably this is defining the objects position and rotation relative to a coordinate system? Can you pop a link to the Environment class?

**Comment by FraserGreenroyd** [comment]
Hi @rwemay code on Env side is here: https://github.com/BHoM/BHoM/blob/master/Environment_oM/Fragments/OriginContextFragment.cs

It doesn't define an objects position, it defines the objects origin as in physical model origin and original element ID which is used across the XML and TAS toolkits currently. I do believe it to be an Environment specific fragment which is why I've never approached @IsakNaslundBh before about a potential common fragment for both disciplines :smile:

**Comment by rwemay** [comment]
Cool, yes in it's current format I don't think would be useful for structures/other disciplines. Will let @IsakNaslundBh pitch in before we close/action further. 

   public class OriginContextFragment : BHoMObject, IBHoMFragment
    {
        public string Origin { get; set; } = "";
        public string ElementID { get; set; } = "";
        public string Description { get; set; } = "";
        public string TypeName { get; set; } = "";
    }
}

**Comment by michaldengusiak** [comment]
great, thanks for discussion
ok perfect I will use `OriginContext` from Environment oM

**Comment by FraserGreenroyd** [comment]
Closing as non-issue then (unless @IsakNaslundBh does decide he wants an `OriginContext` fragment).
