### ISSUE TITLE
Structure_oM: Aluminium and Timber materials do not have SectionProperty equivalents

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#565]
#### Description:
At the moment we have 4 material types in the `oM.Structure` (steel, concrete, aluminium, timber), while only 2 materials are supported in SectionProperties (steel and concrete). This may lead to idiosyncrasies such as steel section with timber material assigned (this happens e.g. on Revit pull of timber elements).

This could possibly be resolved by creating generic sections (#564).

**Comment by IsakNaslundBh** [comment]
Think this is duplicate of https://github.com/BHoM/BHoM/issues/555. If you agree can we close this?

#555 is on the hitlist for 3.0 Beta

**Comment by pawelbaran** [comment]
Sure, apologies for not checking upfront.
