### ISSUE TITLE
Graphics_oM: Add text tag object

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#568]
#### Description:

Add text tag object that contains:

- Point
- string

to be able to return text to be rendable on screen in UIs

**Comment by kThorsager** [comment]
@IsakNaslundBh is this approach still the idea?

And in any case, is the thought to have it in Geometry_oM or should this be a Graphics_oM issue?

**Comment by al-fisher** [comment]
Yes - Graphics_oM I think is right @kThorsager 
And I do think useful

@alelom FYI

**Comment by IsakNaslundBh** [comment]
@rolyhudson think this can be closed based on your work?

**Comment by rolyhudson** [comment]
@IsakNaslundBh yes thanks for flagging. 👍
