### ISSUE TITLE
Geometry_oM: Add ColouredGeomtery obejct

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#569]
#### Description:

Add object with

- IGeometry
- Colour

that can be returned from methods for custom Rendering in UIs

**Comment by kThorsager** [comment]
@IsakNaslundBh is this approach still the idea?

And in any case, is the thought to have it in Geometry_oM or should this be a Graphics_oM issue?

**Comment by IsakNaslundBh** [comment]
@rolyhudson think this can be closed based on your work?
