### ISSUE TITLE
Data_oM: Add Dataset object

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#576]
#### Description:

Need a `Dataset` class to work with all our serialised Datasets used by the Library_Engine.

Object to have properties:

- Source (this might need to be a separate object)
- Date of serialisation
- Data

Question is if this is best put in the Data_oM or if we should add a Library_oM for this. Important to not get this mixed up with any of the work done by @epignatelli 

@al-fisher @adecler @rwemay @FraserGreenroyd @JosefTaylor @enarhi @kayleighhoude @peterjamesnugent  any input welcome.

**Comment by rwemay** [comment]
Talked about this a bit today. Agree source should be very flexible - hyperlink, filepath, paper title/author, code reference, table/figure reference, version/addendum, author(s), publisher, schema, language, region/country, copyright etc etc could all be possible things to store. Perhaps a dictionary (customData) for most of these and just main ones as formal properties (hyperlink/address). 

I think s in Dataset should be lowercase if we call it that.

**Comment by IsakNaslundBh** [comment]
Thanks @rwemay . Happy to go with Dataset (better suits me being Swedish wanting to join up words anyway 😄 )

Regarding all the source info mentioned, almost tempted to add it all in as primary properties. Anyone creating a Dataset will then be reminded of things that would be good to add in, if they have access to the information. Can have a mega create method with all values as default anyway. Can check how out of hand it gets.

**Comment by adecler** [comment]
I agree with @IsakNaslundBh , best to have everything as proper property.

**Comment by al-fisher** [comment]
Agreed!
Also on lower case _'s'_ 😄
