### ISSUE TITLE
Structure_oM: Reinforcement functionality

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM#579]
#### Description:
BHoM currently "has" functionality for Reinforcements in concrete, but you currently can't change the minimum cover value, resulting in sections like this:
![ConcreteWrong1](https://user-images.githubusercontent.com/53530468/66583490-58831080-eb7b-11e9-9245-f0fcef6eb74f.PNG)
And T-sections can similarly not place its reinforcement within the "tie area"
![ConcreteWrong2](https://user-images.githubusercontent.com/53530468/66583608-92ecad80-eb7b-11e9-9bda-9073fc3c0ff4.PNG)

So as I will need to use sections with reinforcement I'm planing to rectify this and expand to make it usable.

### The Plan:

- Move the `MinimumCover` variable from the section to the reinforcement object
- Fix the Create methods with regard to that
- new functional Create methods for things like T-sections
- Update the `Layout()` method which currently places the reinforcement "circles" as it is currently marked as `[NotImplemented]` (yet used)
- Create functionality to extract reinforcement positions from the section object (should not have to be done per toolkit for sanity reasons) (Might be a part of `Layout()` already

#### Secondary smaller Plan

- Calculate the section properties for cracked sections in stage II & III

And since it does not seem to be used in the rest of the BHoM at the moment but will be used after this, it would be nice to get various suggestions on how to restructure it while it doesn't disturb anything, so that we don't have to do it again in the foreseeable future.

@IsakNaslundBh @rwemay  @al-fisher @pawelbaran @JosefTaylor @peterjamesnugent

**Comment by peterjamesnugent** [comment]
I think we should discuss this on the Structures Development call or have a separate dedicated call for this. 

I have some ideas about how to structure this. I think we should have a generic object for the layout of reinforcement bars and this can implemented for pile and bolt arrangements. This would contain:
- Diameter (bar, bolts, reinforcement)
- Link diameter (shear links)
- Cover
- Material
- Points to define location (how this is done may need some thought)

You can then (irrespective of the of the section) write methods for:
- Centroid of the pile/bolt/reinforcement group-
- Number of piles/bolt/reinforcement
- Second moment of area of bolt/pile/reinforcement group

Some ideas for methods/constructors:
- Using the perimeter of a section you could generate a reinforcement layout 
- You could produce layouts using a simple m x n grid

**Comment by peterjamesnugent** [comment]
As discussed on the Weekly Structures Call:
- ConcreteSection to own an IReinforcement
- IReinforcement has LongtudinalReinforcement class, TendonReinforcement, ShearReinforcement class
- ConcreteSection can own multiple Reinforcement objects (longitudinal, shear reinforcement etc.)
- Reinforcement object stores the metadata such as reinforcement diameter, cover, material etc.
- Reinforcement owns an ILayout object 
- IPointLayout has PerimeterLayout, GridLayout, LayerLayout etc.
- ILineLayout has ClosedLineLayout, TendonLayout etc.

![image](https://user-images.githubusercontent.com/30078587/66659705-e0c8ea80-ec3b-11e9-9414-f7fd76e41bdc.png)
