### ISSUE TITLE
Addition of a Dimension Custom Attribute for object Properties

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#581]
Proposal to create an additional optional `CustomAttribute` to be applied to object properties enabling specification of Property `Dimension`. This will be an implementation (in the first instance) of the physical base quantities and their derivatives in the International System of Quantities https://en.wikipedia.org/wiki/List_of_physical_quantities
https://en.wikipedia.org/wiki/International_System_of_Quantities
With scope to expand outside of the physical realm later. 
 
e.g. 

Base quantity | Dimension | SI unit 
-- | -- | -- 
length | **L** | m
mass | **M** | kg
time | **T** | s
electric current | **I** | A
thermodynamic temperature | **ϴ** | K
amount of substance | **N** | mol
luminous intensity | **J** | cd

Derived quantity | Dimension | SI unit 
-- | -- | -- 
area | **L²** | m²
force | **M L T⁻²** | N = kg m s⁻²
etc.

This will mean creating a set of predetermined Quantity Types - specified as a list on enums or similar and passed as an argument into the Custom Attribute

This enables a couple of powerful use cases:

1. in the UI's different default units can be provided depending on a _double_ property's specified dimension.
2. Extending the Quantity Types to have their defined dimensions listed will allow dimensional analysis to be performed in a perhaps a future Dimension_Engine. This can enable additional compliance checks that (where implemented) dimensions/units on both sides of equations are consistent.

Worth highlighting, all the above is assuming SI throughout (as per table above). 
This Dimension_oM/Engine could however be combined with separate Units_Engine as part of UI & reporting.

@rwemay @adecler @IsakNaslundBh @FraserGreenroyd

**Comment by rwemay** [comment]
Beautiful!

**Comment by IsakNaslundBh** [comment]
Really like, think it can be really useful and powerful! Can also maybe extend the use to input/outputs for methods as well?

**Comment by rwemay** [comment]
@IsakNaslundBh , you missed a great convo in HK! We should've dialled you in. Idea is to first have this attribute that lets you tag things with particular dimension, then use Units_Engine etc. to do things like define and switch between units. Without a 'dimension' concept we could still switch but would need to be 'wholesale' between systems - and us needing to define the defaults for whole-systems-at-a-time. Can also then support things like warnings if someone is multiplying/operating on incompatible dimensions. The default will still (obviously) be SI and dimensionless. Also opens the door for allowing string inputs to doubles with some helper text methods like adding 'in' or " to signify inches if a double property has a length dimension attribute.
