### ISSUE TITLE
BHoM_Test: Remove unnecessary dependencies

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM#600]
BHoM_Test project relies on unnecessary dependencies. These should be removed.

@adecler what do you think of just removing the whole BHoM_Test project from core BHoM? I think we discussed it recently but can't remember.

To be actioned w/c 4th November, either removing project (depending on @adecler thoughts) or removing unnecessary dependencies.

FYI: @IsakNaslundBh

**Comment by adecler** [comment]
@FraserGreenroyd , yes, all the `_Test` projects need to be removed from each repo. 
Worth noticing that there is also a Testing_oM in the BHoM
