### ISSUE TITLE
Environment_oM: Calculated construction values fragment

### ISSUE THREAD

**Issue by rboulton-BH** [BHoM/BHoM#615]
#### Description:

It would be useful to have the heavily calculated values from energy modelling software read and stored on constructions as fragments. These include: U-value, g-value, thermal mass Cm, visible light transmission etc.

**Comment by rwemay** [comment]
Maybe worth a chat with @IsakNaslundBh on results/relation ship to objects/their physical counterparts.

**Comment by IsakNaslundBh** [comment]
Happy to have a chat about how we have dealt with this in structures if useful.

As a summary, we have broken out the results from the main objects. No-one of them "own" each other as proeprties/fragements/custom data or something else, but is instead paired up together using IDs taken from the host softwares were the results have been generated.

One main reason for doing this is that you at least in structures easily and commonly end up with thousands of results per element. 

We have common result interfaces as well as various support methods that should work cross discipline if you want to go down the same route.

If you are talking about single values though, as a U-value per wall etc, guess some kind of fragment or similar could work. But again, good to have a chat to try to keep the disciplines as aligned as possible.

**Comment by FraserGreenroyd** [comment]
Discussion with @IsakNaslundBh just now, we've decided that the best way forward to keep alignment between disciplines and allow for build out to other disciplines, is to do the following:

 - Environments Analytical Construction which is `IImutable`, which are similar to the Structure `SectionProperties`
 - Environments Analytical Construction stores all of the possible calculated values for constructions and used when reading from external software only
 - Possible interface for analytical construction in `Analytical_oM` which would be empty and used as a 'tag' for all sub-analytical constructions similar to panels - only change to `Analytical_oM` proposed as part of this work if this bit goes ahead

**Comment by MajaLindroth** [comment]
I am planning to implement the following construction values: 

- U-value
- g-Value
- Thermal mass Cm
- Visible light transmittance 
- Frame factor value? 
- Construction thickness
- R-Value
- Internal emissivity
- External emissivity 
- Internal solar absorptance
- External solar absorptance 
- Internal visible reflectance
- External visible reflectance
- Internal solar reflectance
- External solar reflectance 
- Refractive index
