### ISSUE TITLE
MEP_oM: Discussion following PR

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM#617]
Following the PR review in https://github.com/BHoM/BHoM/pull/591 comments were made which need to be discussed and addressed as appropriate.

This issue is to capture that discussion and formalise any actions necessary for changes to MEP oM off the back of those discussions.

I am assigning the people who need to have the discussion initially, once a decision is reached on what code changes are needed, the issue can be reassigned to myself or someone else who will make the code changes :smile:

FYI to the following people who aren't being assigned for discussion but will want to keep an eye on this so 'subscribing' them through a tag: @al-fisher @rwemay @tg359

**Comment by kayleighhoude** [comment]
**Proposed Additional Concepts/Properties:**
`MEP_oM/Parts/CoolingCoil.cs`
`MEP_oM/Parts/EnergyWheel.cs`

To integrate RelativeHumidity, note to be added to the description stating that 2 of the 3 properties (DB, WB or RH) to be added and the third could be calculated using the psychrometric methods located here: https://github.com/BuroHappoldEngineering/Climate_Toolkit/blob/master/Climate_Engine/Compute/Psychrometrics.cs

`MEP_oM/Parts/EnergyWheel.cs`
`MEP_oM/Equipment/AirHandlingUnit.cs`
The term "Relief" to be replaced by the term "Exhaust"
"Exhaust" to mean air leaving the unit and going to atmosphere

`MEP_oM/Parts/EnergyWheel.cs`
Face Velocity
Pressure Drop 

`MEP_oM/Parts/HeatingCoil.cs`
Fluid Type
Face Velocity

`MEP_oM/Parts/CoolingCoil.cs`
Face Velocity

`MEP_oM/Parts/Fan.cs`
FanEfficiency *modification from Efficiency
MotorEfficiency

`MEP_oM/Parts/Filter.cs`
FilterClass *modification from MERVRating
DesignPressureDrop *in addition to Initial and Replacement Pressure Drops
Face Area
Face Velocity

**Additional Parts to be Added as Result of Comments:**
Acoustical Information
Humidifier
Dehumidifier
Desiccant Wheel
Motorized Damper
Frost Coil

@agnieszkaszymczyk @FraserGreenroyd :)

**Comment by travispotterBH** [comment]
Closed, but further discussion to be had on the MEP_om
