### ISSUE TITLE
Data_oM: DBSCANObject is not IObject

### ISSUE THREAD

**Issue by FraserGreenroyd** [BHoM/BHoM#621]
### Broken rules:
`Collections.DBSCANObject` does not implement the `IObject` interface

#### Suggestions to restore compliance:
Add `IObject` or inherit from `BHoMObject` for the above object.

**By 30th November please**

**Comment by IsakNaslundBh** [comment]
Think this is yours @pawelbaran ? Adding IObject seems like the simplest way to make this compliant to me?

**Comment by pawelbaran** [comment]
Yeah, it is mine. If the only action needed is implementing `IObject` then happy to do it, otherwise can be tight time wise 🤔

**Comment by FraserGreenroyd** [comment]
I don't mind how you do it, as long as by 30th November that object no longer shows up in my reports :wink: 

I would agree with @IsakNaslundBh that adding `IObject` is the quickest and least risky solution, so about 5 seconds of work (plus PR time).

I'll reassign the issue to you @pawelbaran
