### ISSUE TITLE
Structure_oM: Add BarDisplacement results

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#625]
#### Description:

Proposal to add new BarResult class called BarDisplaement.

This will give the full displacement of the bar in global coordinates.

The BarDeformation will then only give the deformation of the bar in relation to its endpoints in local coordinates.

@rwemay @JosefTaylor @peterjamesnugent

**Comment by rwemay** [comment]
Sounds very good.

**Comment by JosefTaylor** [comment]
Careful what you mean by endpoints:
![image](https://user-images.githubusercontent.com/7024203/69366401-51fcb400-0c64-11ea-8017-54f6fad45c50.png)

**Comment by IsakNaslundBh** [comment]
Good point @JosefTaylor . Agree, need to be careful in calculating the local deformations, at least if it is something we do ourselfs.

In terms of getting these results out, I think only Robot has the capability of extracting the deformations (of the ones I have looked at so far). GSA/Etabs only seem to be able to give out the displacements.
