### ISSUE TITLE
Structure_oM: FEMesh default thickness

### ISSUE THREAD

**Issue by ChrisSelf2** [BHoM/BHoM#644]
![image](https://user-images.githubusercontent.com/36225575/57066816-354b5f80-6cc5-11e9-9772-5785f965a415.png)

The engine currently assigns a default zero thickness to FEMesh objects. This causes issues for softwares such as Midas which do not accept zero thicknesses. Instead, a null thickness should be assigned intially.

**Comment by IsakNaslundBh** [comment]
Transferring this to BHoM as oM related

**Comment by IsakNaslundBh** [comment]
Would expand this to check through all properties assigned to elements in Structure_oM. General default should be to default them to null as type, even with default properties, is telling another story.
