### ISSUE TITLE
Data_oM: BatchRequest vs LogicalAndRequest and LogicalOrRequest

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#645]
While reviewing the requests in Revit_Toolkit, I got stuck at two:
- `LogicalAndRequest`
- `LogicalOrRequest`

They seem to be generic enough to sit in a more central repo than Revit_Toolkit. A few questions come to my mind:
- Would there be a use case for that? For example pull only bars that are made of certain profile?
- Currently both requests are handled internally by Revit_Toolkit - if they were moved to BHoM, how much work would you expect to be needed in each/your adapter?
- How does `BatchRequest` correspond to the ones above?

**Comment by IsakNaslundBh** [comment]
Moving them centrally would get an upvote from me. For sure concepts that are generic anough to live outside revit toolkit!

> Would there be a use case for that? For example pull only bars that are made of certain profile?

Yes!

> Currently both requests are handled internally by Revit_Toolkit - if they were moved to BHoM, how much work would you expect to be needed in each/your adapter?

Would be fine with them not being supported straight away out of the box. `BatchRequest` is not supported in any of the structural adapters as it stands for example. Kan then get implemented on a toolkit by toolkit basis as needed.

And not sure about the batch request

**Comment by al-fisher** [comment]
Agreed with all the above! 👍 

Can return generic error stating request type not supported by this adapter?

**Comment by alelom** [comment]
Agree with the move as well. Can definitely see them used outside revit.

**Comment by adecler** [comment]
Agreed too. Mongo definitely comes to mind

**Comment by pawelbaran** [comment]
Cool, I will move the two to Data.oM together with their relevant methods. However, could anyone tell me whether they overlap with `BatchRequest` by any means? Do we have any use case of `BatchRequest` anywhere? Thanks!

**Comment by adecler** [comment]
That I know of:

- https://github.com/BHoM/Mongo_Toolkit/blob/master/Mongo_Adapter/AdapterActions/Pull.cs
- https://github.com/BHoM/Mongo_Toolkit/blob/master/Mongo_Adapter/AdapterActions/Push.cs

**Comment by pawelbaran** [comment]
This issue can be closed - the logical requests got added.
