### ISSUE TITLE
Common_oM : Remove BH.oM.Common.Materials.Material and MaterialType

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#649]
#### Broken rules:
`BH.oM.Common.Materials.Material` and `MaterialType` have been deprecated since 2.3 - Replaced by `BH.oM.Physical.Materials.Material` in `Physical_oM` as well as material fragments in Discipline namespaces

#### Suggestions to restore compliance:

Removal of deprecated class and enums

@adecler @IsakNaslundBh @FraserGreenroyd FYI

**Comment by al-fisher** [comment]
To be scheduled based on outcome of Versioning workshop planned for end of milestone

**Comment by IsakNaslundBh** [comment]
Closing this as Common_oM was removed in https://github.com/BHoM/BHoM/pull/913.

@al-fisher feel free to re-open if you disagree.
