### ISSUE TITLE
Common_oM : Removal of BH.oM.Common.Properties.CompoundLayer & Object2DProperties

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#650]
#### Broken rules:
`BH.oM.Physical.Constructions.Layer.CompoundLayer`  and `Object2DProperties` have been deprecated since 2.3 - Replaced by `BH.oM.Physical.Constructions` objects class in Physical_oM

#### Suggestions to restore compliance:

Removal of deprecated classes

@adecler @IsakNaslundBh @FraserGreenroyd FYI

**Comment by al-fisher** [comment]
To be scheduled based on outcome of Versioning workshop planned for end of milestone

**Comment by IsakNaslundBh** [comment]
Closing this as Common_oM was removed in https://github.com/BHoM/BHoM/pull/913.

@al-fisher feel free to re-open if you disagree.
