### ISSUE TITLE
Rename IBHoMFragment as IFragment

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#651]
As discussed https://github.com/BHoM/BHoM/issues/646#issuecomment-573802526 requirement to rename `IBHoMFragment` and `IFragment`

The fragment interface implements only `IObject` and thus agreed naming convention suggests it should not have "`BHoM`" in the class/interface name.

**Comment by al-fisher** [comment]
@IsakNaslundBh @FraserGreenroyd  - some coordination and planning will be required for this. Thus we should pick up in upcoming sprint calls to schedule and appropriate. Important to do this milestone if possible.

@adecler @alelom

**Comment by FraserGreenroyd** [comment]
Have agreed with @IsakNaslundBh that this will be done next sprint (sprint 4) of 3.1, with the remainder of sprint 3 used to plan the impact of changes to inform the team at large of what will be happening.

**Comment by al-fisher** [comment]
Perfect. Thanks both
