### ISSUE TITLE
Architecture_oM : Remove now deprecated Wall, Roof and Floor classes

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#652]
#### Broken rules:

Remove code for `BH.oM.Architecture.Elements` `Wall`, `Roof` and `Floor` as have now been deprecated since 2.3
All replaced by `BH.oM.Physical.Elements` as part of migration to combined physical namespace

#### Suggestions to restore compliance:

Removal of deprecated classes

@adecler @IsakNaslundBh @FraserGreenroyd FYI

**Comment by al-fisher** [comment]
To be scheduled based on outcome of Versioning workshop planned for end of milestone

**Comment by IsakNaslundBh** [comment]
Handled in https://github.com/BHoM/BHoM/pull/907
