### ISSUE TITLE
Analytical_oM: IResult should implement Immutable interface 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#677]
Any object that implements IResult - must by definition be Immutable - in that any properties it has can not be modified independently.
A result is an output of an upstream process.

**Comment by IsakNaslundBh** [comment]
Have had a look at this, and the only classes implementing the IResult interface that are not immutable atm are the ViewQuality results in Humans_oM. Will raise issue for those to be fixed, then we can safely add the IImmutable interface to the IResult class:

![image](https://user-images.githubusercontent.com/22005920/151323692-c33b981a-f781-4e59-9da5-8c7614120dfd.png)
