### ISSUE TITLE
Dimensional_oM: Matter Element, IElementM

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM#729]
#### Description:
Due partly to a rising need from the ClimateEmergency_Toolkit to be able to Query things related to the material of things, we should add a `IElementM` which handles things related to matter.

This would get a accompanying Matter_Engine which would be to the Physical_Engine what the Spatial_Engine is to the Geometry_Engine, in that it would allow a unified handling of elements with matter (physical objects) and their materials.

The main questions which `IElement`s will work with are:

1. How much matter is there?
2. What kind of matter am I?

#### Extension Methods:
The methods which would be required by the interface at a compliance level for functionality
- `SolidVolume(IElementM)`
- `MaterialComposition(IElementM)`

#### MaterialComposition
where `MaterialComposition()` would return a new class `MaterialComposition` which would contain:
- `List<Physical.Material>` Materials
- `List<double>` Ratios

where `Physical.Material` is composed of:
- `List<IMaterialFragment>` Properties

The `IMaterialFragement` means that each discipline can have a separate definition of what a material is

The Matter_Engine would largely create unified methods to handle this tree of properties which may or may not be present in a transparent manner.

A note is that BHoM does not force any kind of structure to the format of a material and a Physical.Material can contain multiple material definitions through `MaterialFragments` for different disciplines. Which is a good reason to create these overarching methods which would try and scrape the `MaterialFragments` of the useful information while also maintaining transparency about how good the information is. That is by attempting to get the information in different manners by attempting to query the properties and logging by which degree of accuracy it was attained.

#### Climate Emergency
The main things I've seen obstructing workflow in the ClimateEmergency_Toolkit has been a difficulty in obtaining the Volume and a need to define which material to use in each method. This will allow querying the SolidVolume and getting the assigned materials and their proportions, which may be a ClimateEmergency definition or queried from a library based on the other fragments. Would love for some input from ClimateEmergency folks on which specific features would be needed/helpful.

#### Code:
WIP branches for both oM and Engine: `Matter_Enigne-#-Creation-of-Matter_Engine` for those who are interested in seeing some examples of implementation. (note that I am aware that some of the methods do return wrong answers, but it's made to test the system not the results)

FYI @al-fisher @IsakNaslundBh @pawelbaran @michaelhoehn @kayleighhoude @FraserGreenroyd

**Comment by al-fisher** [comment]
Thanks! Great stuff!
As discussed (at great length :smiley:) this as an approach is looking really good. I would suggest you raise draft PRs based on your current prototyping such that we can potentially move any commentary on to the code if needed.
As also discussed - and for all to note. A small select number of Physical objects and Analytical Discipline objects will be used to complete full working prototype. Aiming to complete MVP this final sprint - to then pick up in next milestone for comprehensive implementation as desired.
Targeting:
`Physical.Elements.IFramingElement`
`Physical.Element.ISurface`
`Structural.Element.Bar`
...
