### ISSUE TITLE
Control of oM properties as "Required" not possible through object initialiser auto-create

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#731]
A disadvantage of the auto-generated object initializer create methods is the loss of control of whether a Property is _required_ or not when in the UI.

Would be good to control this from the oM itself as I think is a useful concept. And then reflect though.

#### _One idea would be to flag as a _required_ property by _NOT_ providing a default value?_

Obviously not too dissimilar to the way any C# method (and any of our Create methods using derived properties) is working.
Is there a disadvantage to that?   

As discussed with @IsakNaslundBh could potentially be quite neat and clear.

Obviously if using objects in the code you would need to initialise object properties before using (especially in the case of lists - up until now have in all cases been providing a default empty `new List<>` )
I think this would be a good sacrifice in the name of clarity though. 

Example for `Structure.Panel` 

![image](https://user-images.githubusercontent.com/15924573/75902082-66417700-5e37-11ea-84ec-99b2e3cc7f06.png)

Another option could be to have a `RequiredAttribute` - although we have quite a few attributes already.

Thoughts? @adecler @IsakNaslundBh @FraserGreenroyd all

**Comment by adecler** [comment]
While I do like to keep things small and tidy (a lot), I worry that the price to pay for it is too much in this case. After debating with myself for a bit of the pros and cons of each (full report provided upon request), I concluded that the most important question to consider is this: " Do we have cases where we want to mark a property as required but we also want to set its default value ?". If we can safely guarantee that the answer will always be 'no' than relying on default values for detecting required properties is not only tidier, it is also more elegant. 

As @al-fisher mentioned, a clear example of needing a default value even for a required property is when the property is an enumerable.  I am not sure I agree with is conclusion that it is a fair price to pay though. Having those enumerable being null by default massively increase the risk of crashes. Any loop through them (or Linq method) would also have to be protected by a null check. So we are effectively moving the additional lines of code elsewhere (likely multiple times). We also have to keep in mind that most contributors are not professional developers. Any reduction of null check requirement is a good thing in my book.

I would also mentioned that the way to make properties required by not proving a default value might seem a bit like an another trick you just have to know. I wouldn't say the same thing if the answer to the question above was always 'no' but we have already seen there is at least one case where it is 'yes'. 

I will finish by just showing what `Panel` would look like with the `Required` attribute to mirror the example from Al:

![image](https://user-images.githubusercontent.com/16853390/75946234-84f74a80-5ed7-11ea-8ea3-6059dea50771.png)

Not so bad and it makes it very clear to anyone reading this code that `ExternalEdges` is a required property even without knowing the internal magic of the BHoM.

**Comment by adecler** [comment]
After Framework call, we agreed to implement the `Required` attribute.
