### ISSUE TITLE
Base_oM : Should the base BHoMObject properties be Virtual ? 

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#733]
As discussed with @IsakNaslundBh - should the base `BHoMObject` properties be Virtual?

This came from conversation about exposing `Name` (as required) at the child object level. 
Allows additional `DescriptionAttribute`s relevant to the child class to be assigned to the base properties. 
As well as highlighting _this_ base property is actually additionally relevant to this child class.

For instance Name is useful for all objects - but it is an **_essential defining_** Property for some objects. Like say the `Human` object and many others across disciplines. Good for that property to be _promoted_ to the child level for clarity. 

In the child class you would simple call `override`, potentially set a default if wanted - but also leave off if #731 is a good idea - and then crucially be able to provide a very context specific Description.

@adecler would be good you get your thoughts on this? @IsakNaslundBh and I were thinking it does support the general concept of allowing the BHoM to be highly customisable, not limiting the user/coder.

**Comment by adecler** [comment]
Really good point about the ability to override the description of a property! 

In the spirit of enabling the coder building from our code, every single property should then be virtual, right ? You never know how your code is going to be used or even if a class is ever going to be inherited from.

**Comment by al-fisher** [comment]
Yep - as discussed just now on Framework call - will proceed with implementing `Virtual` on all `BHoMObject` properties now. 
I will raise a separate issue for applying `Virtual` across all Properties across entirety of the oMs - to be scheduled as part of 3.2 milestone.

**Comment by epignatelli** [comment]
Does this include `IObject`s as well?

Adapters `ActionConfig` do inherit from `IObject`. Are we going to make their properties `virtual` as well?

**Comment by epignatelli** [comment]
Okay, I guess https://github.com/BHoM/BHoM_Adapter/pull/223/files#diff-7080db006c5207ee683ccd3612d80171 answers it!
