### ISSUE TITLE
All Properties across all oMs should be Virtual

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#734]
Following #733 agreed that in fact every Property of any object inheriting from `BHoMObject` should be `Virtual` too.

Allows the greatest level of flexibility and allows any developer to override any property and further extend derivative objects should they so wish.

**Comment by al-fisher** [comment]
Have assigned to us three @FraserGreenroyd @adecler - as this will likely require simple planning to instruct @BHoMBot to raise issues/PRs but be coordinated and merged by Toolkit/Project owners. 

As discussed now urgency to merge all simultaneously.

**Comment by FraserGreenroyd** [comment]
The PR https://github.com/BHoM/BHoM/pull/782 achieves this task and the associated issues linked are being closed as appropriate, so I'll close this issue - if anyone disagrees please reopen as appropriate :smile:
