### ISSUE TITLE
Geometry_Engine trim / subtract / split methods

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/BHoM#735]
Below is an operation required for modelling seating bowls. The intention is create Modify methods accepting closed planar curves, trim the bowl and seating rows to allow unconstrained positioning of aisles, tunnels, vomitories and do cookie cutter like operations on the back of bowl. 

This follows identification of this approach (flexible hole cutting) as a key use case for those with bowl modelling experience.

Looking through the BooleanIntersection, BooleanDifference and MeshIntersection methods currently available I have not yet identified which could be of use.

I'm curious if the methods currently exist in BHoM to do so or need implementation? I have implemented similar methods elsewhere and considering converting to BHoM methods.

Before doing so I am wondering if anyone is working on something similar or other suggestions?

The pink extrusion is a cutter (always vertically extruded from a closed curve in XY plane) with which I need to subtract sections from the red polylines and the grey mesh (could be a surface) 
![2020-03-05_11-27-48](https://user-images.githubusercontent.com/6618854/75977578-9ab74080-5ed4-11ea-9b20-9c2f76bef1d2.jpg)
desired result is something like:
![2020-03-05_11-50-16](https://user-images.githubusercontent.com/6618854/75978983-84f74a80-5ed7-11ea-8aad-afc2ad273aff.jpg)

**Comment by IsakNaslundBh** [comment]
@pawelbaran I am not sure if we yet have this type of functionality in the Geometry_Engine?

I think most of the operations we have work on planar geometries (for example all of the boolean methods). But might be some methods I am forgotten about, so will let @pawelbaran responde :smile:

**Comment by rolyhudson** [comment]
This should be in engine. Moving it there now.

**Comment by pawelbaran** [comment]
@IsakNaslundBh is right, support is pretty much limited to planar surfaces. However, looking at the screenshot, all surfaces inside the polysurface are planar, so there is a high chance you will be able to make use of BHoM methods.

**Comment by IsakNaslundBh** [comment]
Just as an a bit FYI @rolyhudson , you can transfer issues between repos in the same organisation:

![image](https://user-images.githubusercontent.com/22005920/75983000-f808bd00-5ee7-11ea-871f-fcc1f167d266.png)

That way you do not need to close the issue and open a new one in the other repo when you want to move it over :) .

**Comment by rolyhudson** [comment]
@IsakNaslundBh  cool thanks 👍
