### ISSUE TITLE
Geometry_oM: Change Cuboid.Depth property to Width

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#737]
#### Description:

Atm dimensions of the cuboid are defined by `Length`, `Depth` and `Height`. Leaning towards the native speakers, shouldn't it be `Width` instead of `Depth` @al-fisher?

**Comment by kThorsager** [comment]
Chipping in as a non-native speaker, I would say `Length` should be `Width`, which might indicate that this is fairly arbitrary and better named by their axis?

Not sure but a suggestion

**Comment by pawelbaran** [comment]
Fair point @kThorsager - probably however we call the dimensions, the XY ones will be ambiguous for some. Now I got stuck tbh 😕

**Comment by al-fisher** [comment]
Also tbh - I think I went round in circles when originally defining!! 🙈

**Comment by pawelbaran** [comment]
Been there for some time without action - I think we can live with the current convention 🙈 closing the issue
