### ISSUE TITLE
Physical_oM: Add Rebar object

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#755]
#### Description:

New object for a single Rebar to be added, after discussion with @pawelbaran and @LMarkowski 

Proposed object:
```
    public class Rebar : BHoMObject
    {
        /***************************************************/
        /**** Properties                                ****/
        /***************************************************/

        public ICurve CentreCurve { get; set; }

        public double Diameter { get; set; }

        public Steel Material { get; set; }

        /***************************************************/
    }
```
Related to https://github.com/BHoM/BHoM/issues/579

**Comment by pawelbaran** [comment]
I like this, however would think of adding:
- `BendRadius`
- `Function` - is it a primary bar, stirrup or hm, some sort of prop? Some basic `enum` could be handy

On top of that, one initial thought: how would you match bars with shape codes? Geometry methods parsing curves?

**Comment by pawelbaran** [comment]
@LMarkowski FYI

**Comment by rwemay** [comment]
Would go with verbose `ReinforcingBar` personally, thoughts welcome. Also wondering whether it should be an interface `IReinforcingBar` and then have different bars like stirrups that implement. Maybe. @pawelbaran you're closer to a "concrete" :) implementation.

**Comment by LMarkowski** [comment]
I think I would stick to defining rebar's function as an enumerable property not different classes. I can imagine two identical (in shape and parameters) rebars having different function so defining them as objects of different classes could be misleading. Yet, I might be a bit to much attached to the Revit's way of thinking and it'd be useful when it comes to the interactions with other software.
Also I think that changing material from `Steel` to `IMaterialFragment`  (or any other interface that would be better and I'm not familiar with) could be profitable in the future.

Also I'd consider adding a class `Hook` to define ends of the bars rather then defining them by the curve (but it might be again _RevitThinking_).

Finally shapecodes. Shape of a curve is not always self-explanatory when it comes to defining the shapecode. Some shapecodes are almost identical in shape (e.g. 00 - 01 or 11 - 12). I think another parameter for that is necessary.

**Comment by IsakNaslundBh** [comment]
Moving this to physical, as I think it lives better in there

**Comment by rwemay** [comment]
SGTM
