### ISSUE TITLE
Geometry_oM: Review of IGeometry and BHoMObjects and applicability for Geometry namespace

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#756]
As discussed previously opportunity to clarify rules for which objects should reside in the Geometry Namespace. Intention has been for these to be Geometry primitives only - but we have necessarily included objects such as `ShapeProfiles` and the` SettingOut` objects such as `Grid` and `Level` largely to manage dependencies.

Option to impose that _all_ objects in Geometry_oM can _only_ be `IGeometry`.
Any Geometrical BHoMObject should therefore be moved to another namespace. We have had trouble defining what that namespace might be in the past! So good to have a focused thought and planning around this.

However we do now have `Spatial `as a namespace coming from our work on formalising the Dimensional Analysis which could perform that purpose for some objects?

We currently do not have a `Spatial_oM` - but I wonder if that could be useful for effectively foundational (and therefore useful across multiples disciplines) Geometrical Entities (that are not geometry primitives).
Like the ShapeProfiles and the SettingOut objects.

Thoughts?
Capturing this issue here now - to get comments - but also suggest we complete the next level detail of our class, namespace and interface mapping/diagram to create a comprehensive picture (including interactions with disciplines Environment and Structure) to plan changes and implementation priorities

@IsakNaslundBh @pawelbaran @adecler @rwemay @kThorsager

**Comment by pawelbaran** [comment]
I like the concept of enforcing all types in Geometry_oM to inherit from `IGeometry` - this sounds like a nice border between Geometry and Spatial. Or am I being too idealistic?

**Comment by IsakNaslundBh** [comment]
> I like the concept of enforcing all types in Geometry_oM to inherit from `IGeometry` - this sounds like a nice border between Geometry and Spatial. Or am I being too idealistic?

Agree with this as well. Keeping Geometry_oM for pure geometry makes most sense to me!

**Comment by kThorsager** [comment]
Yes, I also like this,
but will take this opportunity to mention that we also have things like `TransformMatrix` as `IGeometry`, which is fine as it's a fairly geometrical concept, but we're also using `IGeometry` to mean anything with geometry for methods like `IBounds()`.

So we're saying that `IGeometry` are lightweight geometrical objects, and then using it as objects with geometrical definition (as existing somewhere in 3d space).

Not a huge problem but it is a slight discrepancy between what we mean with `IGeometry` in different places

**Comment by pawelbaran** [comment]
Good point @kThorsager. As mentioned a long time ago (#249), we could consider implementation of `Matrix` class. This could possibly replace `TransformMatrix`. Pushing this forward, it may be worth revisiting [BHoM_Engine #562](https://github.com/BHoM/BHoM_Engine/issues/562)?

**Comment by al-fisher** [comment]
Yes - agreed - good to revist https://github.com/BHoM/BHoM_Engine/issues/562
@epignatelli we have learnt quite a bit about wrapping since original issue also - so good to re-look.

Agreed @kThorsager `TransformationMatrix` is an oddity in `Geometry_oM` too. 
We may decide `Maths_Engine` is just that, only and engine and not oM, as we have the `BH.oM.Data.Collections` already which may be a home for the ~`TransformationMatrix`~ or just `Matrix` ?
@pawelbaran @adecler

**Comment by al-fisher** [comment]
RE `Spatial_oM` for non-primitive Geometrical objects though - sounds like good agreement. 👍 Thanks! Will include in a sketch of foundational namespaces for next milestone planning

**Comment by IsakNaslundBh** [comment]
As discussed in planning, targeting to tackle this in this sprint, initial plan to do it this Friday.

Moving ShapeProfiles as well as levels and grids to Spatial_oM.

@FraserGreenroyd @al-fisher @pawelbaran @peterjamesnugent @JosefTaylor @alelom
