### ISSUE TITLE
Environment_oM: Add AirWall (Hole) type to opening enum

### ISSUE THREAD

**Issue by BingWangUS** [BHoM/BHoM#763]
#### Description:

Add a AirWall (Hole) type to opening enum, instead of using undefined.

**Comment by BingWangUS** [comment]
Thanks Fraser. Sorry do not have the background of this. Me and Michael discussed this and think a hole will make sense but would love to hear why it is not. Adding some names here so forgive me if I at the wrong person.

@rwemay @al-fisher

**Comment by FraserGreenroyd** [comment]
@BingWangUS could you provide the result of the discussion between yourself and @michaelhoehn ?

From the previous discussions, holes don't exist. They're just a part of the wall that isn't there. So it made sense when we last looked at this to just be an `undefined` opening in the wall.

If you're going to want to change my mind, you'll need to provide those discussion notes :wink:

I would suggest getting an input from environments users rather than Al/Rob so I'll tag:

@rboulton-BH @MajaLindroth @MarthaVoul @kayleighhoude @KentonPhillips-BH @cskinnerBH @vbeardow

**Comment by BingWangUS** [comment]
Hi Fraser. Your explanation is clear to me. However, it is not intuitive from my point of view. 

This also apply to panel type, which may be a bigger confusion. My understanding of "undefined" is the default value. For opening, default is a hole, which make sense. But for panel, default as a non-existing wall is not what I would expected. 

Love to hear what others says.

**Comment by kayleighhoude** [comment]
@BingWangUS @FraserGreenroyd I think this could be cleared up with better descriptions on the inputs for type. The default is Undefined for both a panel and an opening, without realisation of the consequences (airwalls and holes in IES). This exact topic came up internally today where there was confusion at the result when not placing a type.

**Comment by al-fisher** [comment]
Reading this, I think there two related issues here. 
One, what does `Undefined` mean in the BHoM for an OpeningType, and 
Two what will different adapters map Undefined to mean in their own software as part of converts. Both can lead to confusion.

@kayleighhoude your point about documenting the assumptions in IES converts in important. Agreed.
i.e. if `OpeningType == Undefined` IES assumes Air etc.
That would address point two.

To address point one and @BingWangUS's question, I might suggest default `Undefined` is a separate category from very explicitly stating `Void` or `Hole` or `Air` (or whatever naming makes sense)

Would be clearer to me at least I think. 
You can then also document to say IES (and any other adapters) automatically map `Undefined` to `Void` or decide to raise a warning instead to warn user to make sure they are explicit with their assumptions. Depending on what you think is most natural/best. 

``` 
        Undefined,
        CurtainWall,
        Door,
        Frame,
        Glazing,
        Rooflight,
        RooflightWithFrame,
        Window,
        WindowWithFrame,
        VehicleDoor,
```
I wonder if that makes sense?

**Comment by charliebrookerBH** [comment]
Hi team, adding my weight to the point @BingWangUS raises - personally having a "Hole" opening type makes sense to me coming from IES terminology, and will probably be most familiar to others coming to use the BHoM from S&P. 

I like how @al-fisher is suggesting implementing it. I'd propose that OpeningType == Undefined for IES (and gbXML more generally) assumes Glazing. IES models don't work if there are external holes, and glazing is the most used opening type when working with thermal simulations.

**Comment by charliebrookerBH** [comment]
Hi team, how did you deal with this in the end?

**Comment by FraserGreenroyd** [comment]
Hi @charliebrookerBH, there is now have a `Hole` option on `OpeningType` dropdowns (or will do from today's alpha). This is then handled in XML, IES, and TAS toolkits in the same was a `undefined` was previously.

The full list of opening types is now:

```
Undefined
CurtainWall
Door
Frame
Glazing
Hole,
Rooflight
RooflightWithFrame
Window
WindowWithFrame
VehicleDoor
```
