### ISSUE TITLE
Structure_oM: MeshResult constructor should take a list as input instead of a ReadOnlyCollection should 

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM#773]
#### Broken rules:
No broken rule per se (yet! @FraserGreenroyd  ?). The idea is that there is no simple way to build a `ReadOnlyCollection` from the UI so this should not be a type used as parameter. 

#### Suggestions to restore compliance:
Do the same as for any other constructor of classes that contain ReadOnlyCollection, use list as input.

**Comment by IsakNaslundBh** [comment]
Yeah, fine with making this change. Will make it easier to use as well.

I assume `IEnumerable<MeshElementResult>` would work fine as well, for terms of deserialisation?

**Comment by FraserGreenroyd** [comment]
@adecler I can produce the rule and add it to the wiki if we would like to now enforce a 'ban' on the use of `ReadOnlyCollection` within the BHoM framework? :smile:

**Comment by adecler** [comment]
> I assume IEnumerable<MeshElementResult> would work fine as well, for terms of deserialisation?

Yes, it seems to be what is used in most other constructors

> @adecler I can produce the rule and add it to the wiki if we would like to now enforce a 'ban' on the use of `ReadOnlyCollection` within the BHoM framework? 😄

This can actually be used as property (of Immutable objects), it is just recommended not to use it as a parameter of a method.

**Comment by IsakNaslundBh** [comment]
Was resolved by https://github.com/BHoM/BHoM/pull/912
