### ISSUE TITLE
Diffing_oM: HashFragment should not have a constructor

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM#774]
#### Broken rules:
Even if it is not a BHoM object, HashFragment should not have a constructor. This basically prevent reflection and serialisation to work properly with that type of object.

#### Suggestions to restore compliance:
Delete constructor

**Comment by alelom** [comment]
I realised I missed to implement `IImmutable` but that was the intention. Corrected in https://github.com/BHoM/BHoM/pull/776
