### ISSUE TITLE
BHoM: Revisit the concept of BHoMGuid

### ISSUE THREAD

**Issue by adecler** [BHoM/BHoM#784]
- When is it persistent ? When is it changing ? 
- It seems we all like lazy initialisation of Guid : BHoM/BHoM#303 to improve computational time. That also means we need to make sure that Explode for example is not outputting Guid by default unless asked to.
- We also need to clarify conventions around the Modify method (clone vs create new vs modify input directly). This links with the Immutability preserved at the level of the UI vs in the method itself.

**Comment by al-fisher** [comment]
I think we should be looking at renaming the `BHoMObject.BHoM_Guid` to simply `BHoMObject.Guid` also.
Raised separate issue [here ](https://github.com/BHoM/BHoM/issues/786)- but to likely be coordinated at least.

**Comment by adecler** [comment]
Other relevant issue: https://github.com/BHoM/BHoM_Engine/issues/1826

**Comment by adecler** [comment]
Closing as handled in https://github.com/BHoM/admin/issues/9
