### ISSUE TITLE
BHoM: Rename base BHoM_Guid as simply Guid

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#786]
Following discussion and work on renaming old BHoMFragment etc. https://github.com/BHoM/BHoM/issues/646#issuecomment-573802526 and https://github.com/BHoM/BHoM/issues/651 
makes sense I think to remove the prefix of `BHoM` for the parent GUID property I think?

With `BHoMObject.BHoM_Guid` to simply become `BHoMObject.Guid`.

To be closed out with https://github.com/BHoM/BHoM/issues/784 most likely 

Assigning you @adecler inline with above issue and to coordinate. Non-critical obviously

**Comment by adecler** [comment]
As agreed from Framework workshop:

Keeping the property name as is makes it simpler to search and fileter it. Ids are generally present in a lot of classes so keeping it as `BHoM_Guid` keeps it very explicit that this is the Id related to the BHoM even if the object contains multiple Guids.

**Comment by alelom** [comment]
Adding to that: 
we considered that the Guid is really tied to the place it's been generated from. We want to be able to easily distinguish between a Guid that e.g. has been extracted from an external software and the one generated by BHoM.  
This clearly distinguish it as a BHoM Object property from, for example, `BHoMObject.Name`. If we use the same name for an object that is in an external software or in the BHoM it does not matter, it's a valid choice; but for the Guid we need to make a clear distinction in all cases.
