### ISSUE TITLE
Geometry_oM: Add explicit casts between curve types.

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/BHoM#789]
#### Description:

To help the UI out for some curve types, that could be defined in many different ways with the same result, suggesting to add a few explicit casts in the Geometry_oM between the BHoM curves.

for example

- Line -> PolyLine
- Line -> NurbsCurve
- Line -> PolyCurve
- PolyLine -> PolyCurve
- PolyLine -> NurbsCurve

and potentially the other way around (with checks).

This would make the coverts in the UIs a lot simpler to deal with, as you only have to return one thing (maybe the most simple possible) and can let the explicit cast to what the method wants.

Would hopefully help solve issues like 2-noded `Polylines` not feedable to a BHoMComponent expecting a `Line` etc.

@adecler can you see any downside with adding this?

@pawelbaran @al-fisher @adecler @FraserGreenroyd @epignatelli @alelom @kThorsager

**Comment by FraserGreenroyd** [comment]
Title says Geometry_Engine but this is posted on BHoM so I'm guessing that's just a typo?

I'm not convinced this is the right solution in terms of the BHoM philosophy, we've managed to survive this long without these converts, why do we need to add them now?

Why can't they be convert methods within the Geometry_Engine which then makes it very explicit to the user what they can and cannot convert between. This also prevents any 'accidental' converts happening - the user must be very conscious of dropping a convert component on a canvas.

That's my tuppence anyway, but I'm not a big geometry maintainer so happy to leave the big guns to the debate mostly!

**Comment by pawelbaran** [comment]
> I'm not convinced this is the right solution in terms of the BHoM philosophy, we've managed to survive this long without these converts, why do we need to add them now?

Because life should not be about survival, but about comfort (even though it might look a bit different recently).

> Why can't they be convert methods within the Geometry_Engine which then makes it very explicit to the user what they can and cannot convert between. This also prevents any 'accidental' converts happening - the user must be very conscious of dropping a convert component on a canvas.

Well, the need for explicit convert is the actual issue here @FraserGreenroyd - the end user does not want to bother about the difference between 2-point nurbs curve, 2-point polyline and a line. Plus, Grasshopper does already so many 'accidental' converts that it will not make too much difference if we add a few 😆

**Comment by adecler** [comment]
@IsakNaslundBh , I have no problem with doing that.

@FraserGreenroyd , This is already part of the BHoM conventions to do this. See documentation: https://github.com/BHoM/documentation/wiki/BH.oM-%E2%80%90-Define-New-Objects#casting-methods

**Comment by epignatelli** [comment]
I think that from the user point of view, even programmer would make sense. On the other hand it would introduce a more complexity in maintaining the code, not in the oM, but in the UI converters, such as the Rhinoceros_Toolkit. But maybe I am wrong, maybe it would help. 

I would just make sure that if we pr this, we also re-check the validity of the Rhinocerso `Convert`s.

**Comment by adecler** [comment]
On the side of the UI component inputs/outputs, it already works for things like` Point -> Node` or `string -> DataViz.Dimension`. So it should work for any other case. 
I would have to check if there is any impact on teh visualisation of the geometry in Grasshopper. @epignatelli , you probably know better than me on that one.

**Comment by epignatelli** [comment]
Yep! I'll keep track of it as soon as the pr is issued!

**Comment by pawelbaran** [comment]
@adecler not only Rhino, but also Dynamo and Revit.

**Comment by IsakNaslundBh** [comment]
Cool, thanks for comments all.

In terms of visualisation, I cant see this being an issue, as if I am not mistaken, the explicit casting is on used when collecting the inputs (correct me if I am wrong here @adecler ).
Also, good reason of using explicit rather than implicit. It should only happen if you explicitly cast it, not by some random event, ending up in a unexpected method.

I think a first suggestion, in support of dynamo, is to add:
- Polyline -> PolyCurve
- Polyline -> NurbsCurve

This is to support the issue that dynamo does not have a definition of a polyline.
Adding those converts, we could check any polycurve/nurbscurve coming from dynamo if it only contains line segments, or is of degree 1, and if so, return a polyline. Then if the method used assumed a nubrs/polycurve, it would go Dyn.Polycurve -> BH.Polyline -> BH.Polycurve and still work, while we would be able to have some sort of supports for polylines in dynamo.

Can then ofc fill up with more, such as

```
        /***************************************************/
        /**** Explicit Casting - Special Case           ****/
        /***************************************************/

        public static explicit operator Line(Polyline polyline)
        {
            if (polyline.ControlPoints.Count == 2)
                return new Line { Start = polyline.ControlPoints[0], End = polyline.ControlPoints[1], Infinite = false };
            else
                return null;
        }

        /***************************************************/

        public static explicit operator Line(NurbsCurve nurbsCurve)
        {
            if (nurbsCurve.ControlPoints.Count == 2 && nurbsCurve.Knots.Count == 2)
                return new Line { Start = nurbsCurve.ControlPoints[0], End = nurbsCurve.ControlPoints[1], Infinite = false };
            else
                return null;
        }

        /***************************************************/
```

which would be more nice to haves, rather than critical for a particular UI.
