### ISSUE TITLE
MEP_oM: Implement IElementM

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM#808]
#### Description:

Implement the interface `IElementM` for appropriate objects:

- [ ] `AirHandlingUnit`
- [ ] `FanCoilUnit`

and any other objects for which it would make sense. 

And implement the required extension methods in the Engine

- `MaterialComposition()`
- `SolidVolume()`

**Comment by FraserGreenroyd** [comment]
As discussed with @kThorsager the object mentioned do not contain the required properties to make them valid for `IElementM` at this time.

@michaelhoehn and @kayleighhoude be advised though - eventually objects here will need to do this.
