### ISSUE TITLE
LifeCycleAssessment_oM: Consolidate oM into folders

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM#818]
#### Description:
Consolidate scope objects for MEP/TI/Structures into disparate folders for ease of use/navigation
![image](https://user-images.githubusercontent.com/34316256/79900348-149b7e80-83dc-11ea-8164-a75cf5add054.png)

**Comment by michaelhoehn** [comment]
Closing this issue as it is no longer relevant. This organisation was refactored last year and are no longer discrete objects, but IElementM.
