### ISSUE TITLE
Architecture_oM: Should Ceiling remain?

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM#830]
https://github.com/BHoM/BHoM/blob/12955da8af2f1974541ee24114904128be57994b/Architecture_oM/Elements/Ceiling.cs#L28-L40

This looks a lot like

https://github.com/BHoM/BHoM/blob/12955da8af2f1974541ee24114904128be57994b/Architecture_oM/Elements/Floor.cs#L33-L46

which was moved.
Should this be deleted, moved or remain?

(it also has non of the extension methods for `IElement2D`)

@al-fisher @pawelbaran @IsakNaslundBh @rwemay

**Comment by IsakNaslundBh** [comment]
@kThorsager Not sure why this lives in Architecture instead of Phsyical.

@FraserGreenroyd  looks like you added this, you might be better placed to answer?

**Comment by FraserGreenroyd** [comment]
From memory of the discussions that happened when the Ceiling object was put in, the Ceiling object is (meant to be, though not all properties got defined at creation) the analytical representation of the architectural ceiling. In the physical world, a floor is capable of being a ceiling based on where you're looking at it (whether you're standing on it or under it), but in the architectural world, a ceiling is different from a floor in terms of what it might store.

There is also a possibility for a ceiling to be lower than a floor between levels, useful for when MEP store MEP equipment between a false ceiling (which would still be a ceiling) and the physical floor of the level above.

From this discussion, I am not seeing a convincing reason for changing that previous decision.

**Comment by kThorsager** [comment]
It's that object-wise it's identical to the `Physical.ISurface` and moving it there would expose all of that functionality compared to the no methods in the Architecture_Engine, and would make it's `IElement2D` work without copy-pasting the methods from Physical.
(and add `IElementM` and its functionality)

If that's not convincing enough I'll leave it as is

**Comment by FraserGreenroyd** [comment]
It's not convincing enough to me to move it today because I know the MEP guys are continuing to work out what else they need from the ceiling object. One of the things currently in the pipeline is the ceiling tile patterns being pulled from Revit to aid with sprinkler placements, etc. - for which I do not see moving that to physical will overly help alas.
