### ISSUE TITLE
Data_oM: Spatial data class for data with extents

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM#843]
#### Description:
Will start of by saying that I'm quite biased towards creating some kind of `RTree`

I know of `PointMatrix`

- Mainly dislike that it is very dependent on the initial cell size.
- There's also the difficulty in adapting it for data with extent (i.e. `ICurves`) as it is defined for Points. Now, I do think that it's possible, but it strikes me as building out on mismatched foundation.
- No "good" solution for closest item, as the solution without a max distance would involve stepping out cell by cell until it found something, which would be very inefficient if the closest item isn't close to the search point. 
(And the uninitiated might take it as more of an arbitrary upper bound and set it as distance from the search point to the first point to search among. Both causing issues when it tries to sort every point in the search set and when it tries to Query every empty cell between the search point and the points to search among if one say happened to pull a Revit model in the wrong coordinate system and searched from a static source)

A spatial data tree would also have some initial values to consider, namely:

- Sub branches per branch
- number of items in the end branches

But they won't be as scale dependant and a faulty value won't be as detrimental as for the `PointMatrix`. That is as the worst case would be having every item in one branch, which would equate to not having an tree structure.
A faulty value for the `PointMatrix` could lead to the need to check an arbitrary amount of cells. 
(which isn't really a fair comparison as that would be an extreme case which most in-code users would safeguard from, but difficult to keep from being able to happen centrally)

So would propose adding an Spatial Data Tree class which can handle elements with extents and would be happy to implement it.

Otherwise I'll have a look at fixing up the `PointMatrix` situation.

@pawelbaran @al-fisher @adecler Give me a go ahead if this is fine, and add anyone else who gets a say in this

**Comment by adecler** [comment]
I have no issue with you adding an alternative to the `PointMatrix`. As always, it is great to have multiple options.

Adding @rolyhudson as he might be interested too.

**Comment by al-fisher** [comment]
Yes - agreed! Sounds good to me too

**Comment by rolyhudson** [comment]
This sounds great. I can see this being really useful for geospatial scale queries too.
