### ISSUE TITLE
Geometry_oM: Add new wiki page to document the explicit casts between geometry primitives

### ISSUE THREAD

**Issue by al-fisher** [BHoM/BHoM#850]
#### What is missing/incorrect?

As discussed on Foundational Sprint Kick-Off call just now - as we plan to implement some more critical explicit casts - good to create clear documentation of when and why they are implemented.

Agreed a nice matrix showing for each pairing of primitives - highlighting where explicit casts do exist - and with a notes column explaining logic of primary reason it is needed or indeed not implemented/excluded.

@IsakNaslundBh @adecler FYI

**Comment by kThorsager** [comment]
Made a first draft on a wiki page:
https://github.com/BHoM/BHoM/wiki/Geometry_oM:-Explicit-casts
Think it became quite good, but please do check it out and complain wherever necessary

**Comment by al-fisher** [comment]
Very useful and comprehensive. Thanks @kThorsager - happy to close this as certainly addressed.
