### ISSUE TITLE
Environment_oM: Modify Space Object

### ISSUE THREAD

**Issue by kayleighhoude** [BHoM/BHoM#882]
#### Description:
Modify environment space object to include new properties:
Acoustics
OccupantDensity
Exhaust
FireProtection
Edit the Infiltration Gain property to just be Infiltration
Edit the Space Type to take in a string rather than an enum (to give flexibility)
![image](https://user-images.githubusercontent.com/34316256/82491698-fc8a4e00-9ab2-11ea-8d4c-5cef9177fc8b.png)

**Comment by FraserGreenroyd** [comment]
Following discussion with @kayleighhoude :

SpaceType as enum will stay but additional string property for project space type will be added.

Spelling of ventilation will be corrected on namespace for ventilation object.
