### ISSUE TITLE
Common_oM: Remove Common_oM

### ISSUE THREAD

**Issue by kThorsager** [BHoM/BHoM#887]
#### Broken rules:
A tad to general in scope.
And most objects have inside have been deprecated.

#### Suggestions to restore compliance:

1. Migrate IPhase and similar objects to Planning_oM #885 
2. Remove dependencies and using statements from Architecture_oM (Other references should be resolved with the results) #886 
3. Migrate `IResult` and similar objects, ~not covered by this issue~ issue https://github.com/BHoM/BHoM/issues/903
5. Remove dependencies in the template https://github.com/BHoM/documentation/issues/31
6. Remove the oM #887  and Engine https://github.com/BHoM/BHoM_Engine/issues/1794

(1 to 3 are not dependant on each other)

Will have this as the general coordination issue

FYI and confirmation @al-fisher @adecler @rwemay

**Comment by al-fisher** [comment]
FYI @kThorsager added new issue for `IResult` here: https://github.com/BHoM/BHoM/issues/903
