### ISSUE TITLE
Structure_oM: rename RigidLink master/slave nodes

### ISSUE THREAD

**Issue by JosefTaylor** [BHoM/BHoM#921]
While it's only a tiny brick in the gargantuan wall that is structural racism, it seems like a good day to quietly re-name MasterNode and SlaveNodes to something without the pain embedded in those terms.

I suggest Planet/Satellite or Sun/Planet, or maybe Base/Remote

The important thing to illustrate with these names is that the head/sun/base owns the coordinate system that defines the constraint between it and the other nodes.

**Comment by maryannewachter** [comment]
Maybe source/remote?

**Comment by IsakNaslundBh** [comment]
Another suggestion:

Primary/Secondary

**Comment by al-fisher** [comment]
Thanks @JosefTaylor for raising this. Totally agreed!

**Comment by al-fisher** [comment]
Building on your suggestions above ... how about Origin and Satellites ?

**Comment by andrewtclark** [comment]
I suggest picking something that seems to be aligned with what the rest of the broader comp. sci./coding community is settling on. I'm sure we're not the only folks consdiering this at the moment by a long shot. Its fun to get creative until you're stuck explaining esoteric terms for the ten thousandnth time! A quick google search shows a very vibrant debate going on, with Github itself suggesting possibly main/replica or something along those lines?
