### ISSUE TITLE
Physical_oM: Strange behavior for location surface / external edge with external edge not closed error

### ISSUE THREAD

**Issue by enarhi** [BHoM/BHoM#924]
#### Description:
Occasionally certain Physical.Floor objects throw this error when doing set property and other methods indicating that the external edges are not closed. It appears something about the stored Location surface is causing the issue, as methods like SolidVolume() fail as a result.

![image](https://user-images.githubusercontent.com/6752345/84953206-f84c5300-b0a7-11ea-937c-8b72568eaa34.png)

#### Steps to reproduce:
See test script below, this seems especially common when using floor objects after pulling them from Revit.

#### Expected behaviour:
These objects should not have the external edges open error, and calculations like SolidVolume() should work properly with them.

#### Test file(s):
[PhysicalFloors-ErrorForExternalEdges.zip](https://github.com/BHoM/BHoM/files/4795205/PhysicalFloors-ErrorForExternalEdges.zip)

**Comment by enarhi** [comment]
@pawelbaran I suspect this may be unique to floors coming from Revit, so I created [This Issue](https://github.com/BHoM/Revit_Toolkit/issues/754) in Revit_Toolkit as well that may take care of this.

**Comment by pawelbaran** [comment]
I am closing this as https://github.com/BHoM/Revit_Toolkit/issues/754 got resolved with https://github.com/BHoM/Revit_Toolkit/pull/796.
