### ISSUE TITLE
Mismatch in LifeCycleAssessmentScope Language

### ISSUE THREAD

**Issue by ajensen19** [BHoM/BHoM#929]
#### Description:
Not exactly a bug but just a mismatch in this component between the "ProjectArea" which is accepted a category derived from the CLF benchmarking categories and is technically based on ft2, and the "ProjectActualArea" which is seeking a m2. 

I think these fields should probably agree with each other so perhaps we just revise the accepted categories to be in m2 (per the alternative snip), the native CLF dataset that would have the full list of alternative taxonomy for the m2 categories : https://burohappold.sharepoint.com/:f:/r/sites/LifeCycleAssessment/Best%20Practices%20Library/Resources%20and%20Research/Tools%20and%20Datasets/CLF-Embodied-Carbon-Benchmark-Report-and-Data?csf=1&web=1&e=WUHj4z

See image below documenting this: 
![image](https://user-images.githubusercontent.com/19961672/84936477-46615680-b0a8-11ea-9ba6-c7ef29d3a1a1.png)

![image](https://user-images.githubusercontent.com/19961672/84936825-d4d5d800-b0a8-11ea-92b8-dca8adf2d8d3.png)

**Comment by michaelhoehn** [comment]
Transferring this issues as it relates to the ProjectArea enum within the LCA_oM.
