### ISSUE TITLE
Global: Any chance to add support for Sofistik?

### ISSUE THREAD

**Issue by netsonicyxf** [BHoM/BHoM#931]
https://www.sofistik.com/products/finite-elements/sofistik-2020-highlights

The most powerful structural / geotechnical analysis and design pacgake for structural engineers.

Sofistik also develops grasshopper and dynamo components, but both of them lack a lot of functions comparing to its command line editor "Teddy".

**Comment by JosefTaylor** [comment]
@netsonicyxf We recently looked into buying Sofistik in one of our offices, but nothing happened yet. If you've got a license and want to start a toolkit we'd love to see it! Reach out to @al-fisher if you want to start something.

**Comment by al-fisher** [comment]
Hi @netsonicyxf - been a while since you raised this issue - however a Sofistik adapter is now in the works... see here https://github.com/BHoM/Sofistik_Toolkit - with @felipebandeiramm and @jukkasus leading on this 😄
