### ISSUE TITLE
GUID change history log

### ISSUE THREAD

**Issue by AndreBalasian** [BHoM/BHoM#932]
#### Description:

There is a need to find an effective method of recording historical changes to GUIDs for specific objects such as rooms, spaces and other elements in a model.
In ideal circumstances GUIDS should never change, but they often do in BIM when 3D objects are often recreated instead of being edited, resulting in a new GUID being generated. Therefore a historical GUID change log is needed to maintain an audit trail.
There was a suggestion to use Fragments for this purpose, which is something to look into.

**Comment by adecler** [comment]
As discussed in https://github.com/BHoM/admin/issues/9, Guids should never change. 

If there is a need to records Ids outside the BHoM, then, yes, fragment are the way to go. This is however no an issue for this repo. I suggest you migrate this issue to the relevant toolkit.
