### ISSUE TITLE
Base_oM: Investigate generic Fragments

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/BHoM#937]
#### Description:

While working on BHoM <=> Revit parameter interop, we've identified the need for a fragment that would behave like a dictionary, with unknown number and type of properties - something similar to [ExpandoObject](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.expandoobject?view=netcore-3.1).

Since the above is `sealed`, it will rather not fit the purpose, therefore we need an alternative. I will give it a shot to prototype something in the coming weeks, ideas welcome!

**Comment by adecler** [comment]
mainly around the idea of being able to explode the fragment and get its content instead of something like a dictionary.
@pawelbaran to investigate.

**Comment by pawelbaran** [comment]
Handling of Revit parameters has been handled differently in the end, so the feature is not needed any more from my perspective.
