### ISSUE TITLE
Base_oM: BHoM.CustomData does not speak German

### ISSUE THREAD

**Issue by MartinHenriksen** [BHoM/BHoM#98]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by FraserGreenroyd** [comment]
This issue is not suitable to address owing to the issue being archived and no recent requirements for it to be completed.

From memory, the workflow described pinpointed the issue in script usage, rather than an issue in BHoM Custom Data that could be resolved on this side.
