### ISSUE TITLE
Can we change ILink implementation to be non generic?

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/BHoM#987]
Planning longer term use of `Graph` as an analytical element. (This question relates to https://github.com/BHoM/BHoM/issues/988)

It may very useful to use the `ILink` interface to construct relationships between Nodes of different types. 

Currently the `StartNode` and `EndNode` properties are constrained to a single Type that implements `INode`

What are the benefits of constraining as currently implemented?

What about switching to  a non-generic version like
```C#
public interface ILink : IBHoMObject, IAnalytical, IElement1D
    {
        /***************************************************/
        /**** Properties                                ****/
        /***************************************************/

        INode StartNode { get; set; }

        INode EndNode { get; set; }

        /***************************************************/
    }
```
Thoughts on this @IsakNaslundBh, @FraserGreenroyd, @al-fisher, @adecler ?

**Comment by FraserGreenroyd** [comment]
Can we move this to the discussions tab please and discuss there :smile:
