### ISSUE TITLE
MEP_oM: Add Cable Tray definition

### ISSUE THREAD

**Issue by tiagogrossi** [BHoM/BHoM#997]
#### Description:
Similar to #952 , we could benefit of having the obj definition for Cable Trays. Initial properties can be as with Duct, removing only `FlowRate` as it's irrelevant for it.

**Comment by tiagogrossi** [comment]
@kayleighhoude  and @michaelhoehn  are you two happy for me to pick this up? Afterwards I'll implement the necessary converts.

**Comment by FraserGreenroyd** [comment]
Please go ahead for a first pass @tiagogrossi but be aware it won't be merged into the beta as it is a feature 😄 but I'm sure @michaelhoehn and @kayleighhoude will enjoy reviewing a draft this week ready to go in next week

**Comment by michaelhoehn** [comment]
Had a chat with @tiagogrossi today. He will be providing a draft PR of oM and Engine updates to review with the hopes of merging early in the next milestone! Looks really promising and happy to have the objects within the BHoM 😄
